### ISSUE TITLE
rvierdiiev - lockQuote should lock exactly filledAmount that partyB is going to open for Limit orders

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#103]
rvierdiiev

medium

# lockQuote should lock exactly filledAmount that partyB is going to open for Limit orders

## Summary
lockQuote should lock exactly filledAmount that partyB is going to open for Limit orders
## Vulnerability Detail
partyA can create qoute with some quantity that it would like to be fulfilled.
Orders can be limit and market. When position is open for market order then partyB [should fill all order](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L134). But for limit order it [just should not be 0](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L129-L132).

When partyB locks qoute, then it's not available for anyone else. And the whole qoute is locked.

This is actually not good for partyA.
Let's check example.
1.partyA creates long limit order with quantity 100 at price 1500.
2.partyB immediately locks it.
3.after some time partyB open position for only 1 quantity, because it sees, that prices has changed and it's not favorable anymore or because it can't fulfill all order.
4.Now this order becomes pending with quantity 99. But some time already passed and partyB will likely not lock it, because prices have changed. But if initial partyB locked only 1 quantity, then another partyB might lock another amount and user's qoute can be fulfilled.

So there are 2 problems here.
1.Not honest partyB will execute only small part of quantity to avoid losses.
2.When partyB locks all order and fulfills not whole amount, then all quantity is locked and can't be fulfilled by another partyB. At the moment, when qoute will become pending again prices can change.
## Impact
partyB can use this to avoid losses.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Maybe you can allow to lock only part that should be fulfilled.

Duplicate of #253

**Comment by rvierdiiev** [comment]
Escalate
As it was stated in a lot of another escalations, protocol currently doesn't have ability to block 1 or several partyB, because only allow list exist. So sponsor's suggestion, about stop working with partyB is not easy to do for partyA.
While malicious partyB will be able to generate profit using such strategy, as it can do this not with only 1 partyA, but with hundreds, thousands.

**Comment by sherlock-admin2** [comment]
> Escalate
> As it was stated in a lot of another escalations, protocol currently doesn't have ability to block 1 or several partyB, because only allow list exist. So sponsor's suggestion, about stop working with partyB is not easy to do for partyA.
> While malicious partyB will be able to generate profit using such strategy, as it can do this not with only 1 partyA, but with hundreds, thousands.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@rvierdiyev 
- partyB can be suspended.
- quotes can have deadline
- parties can unlock within the deadline. 
There is no issue here.

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #253 
After further review, this has the same underlying issue as #102 and #253 although a slightly different attack. 
Making this a duplicate of #253

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/103/#issuecomment-1655178484): accepted
