### ISSUE TITLE
Ch_301 - Liquidators are not able to  liquidate the position at the right time

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#125]
Ch_301

high

# Liquidators are not able to  liquidate the position at the right time

## Summary
In [this part](https://docs.symm.io/protocol-overview/capital-efficiency#open-interest-oi-to-total-value-locked-tvl-ratios) from Docs
```diff
SYMM IO has an available OI to TVL ratio of 24.76
```
But the contract doesn't check that.
 
## Vulnerability Detail
PartyA could [sendQuote()](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacetImpl.sol#L21-L120) to any market with big leverage (e.g. x100)
this is not healthy for the protocol, especially with the volatile markets. where the price could move very quickly. Leaving the liquidators on an impossible mission to liquidate the position with `NORMAL` or `LATE` liquidation type. so in this scenario, you are gratin the liquidation type is always `OVERDUE`.
Leaving the other side with no profit and of course no `CVA` (Credit Valuation Adjustment).

## Impact
- Users are able to set the leverage to any big value
 - Liquidators are not able to liquidate the position at the right time
 
## Tool used

Manual Review

## Recommendation
Set Max to the leverage

**Comment by Ch-301** [comment]
Escalate

The other side will never receive any profit. this scenario will keep happening in the volatile markets
```
...you are gratin the liquidation type is always OVERDUE.
Leaving the other side with no profit...
```

Also, the [Docs](https://docs.symm.io/protocol-overview/capital-efficiency#open-interest-oi-to-total-value-locked-tvl-ratios) is defining the available OI to TVL ratio (which is the leverage) of the BTC market to be up to 24.76

```
Open Interest (OI) to Total Value Locked (TVL) Ratios
A key metric to gauge the performance of these platforms is the ratio of Open Interest (OI) to Total Value Locked (TVL). Here's how they compare for shorting BTC:
- SYMMIO has an available OI to TVL ratio of 24.76.
...
```
But users can set OI to TVL ratio to any value

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The other side will never receive any profit. this scenario will keep happening in the volatile markets
> ```
> ...you are gratin the liquidation type is always OVERDUE.
> Leaving the other side with no profit...
> ```
> 
> Also, the [Docs](https://docs.symm.io/protocol-overview/capital-efficiency#open-interest-oi-to-total-value-locked-tvl-ratios) is defining the available OI to TVL ratio (which is the leverage) of the BTC market to be up to 24.76
> 
> ```
> Open Interest (OI) to Total Value Locked (TVL) Ratios
> A key metric to gauge the performance of these platforms is the ratio of Open Interest (OI) to Total Value Locked (TVL). Here's how they compare for shorting BTC:
> - SYMMIO has an available OI to TVL ratio of 24.76.
> ...
> ```
> But users can set OI to TVL ratio to any value
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
Since partyB is **not required** to accept partyA's quotes, if partyA quote has unreasonable leverage, it will simply be ignored by all partyBs. I believe that the idea is to let the market decide the best leverage without limiting it explicitly from the protocol side: each partyB can have its own max leverage it's willing to accept, so leverage limit will happen naturally.

**Comment by Ch-301** [comment]
I see your approach. But this does not refute the two points (issues) in the above escalate, so they still exist.

**Comment by hrishibhat** [comment]
@Ch-301 in addition to @panprog's comments I still do not see the impact for a medium issue here. 
The docs do not expect the ratio to be enforced, but mention the availability.

**Comment by Ch-301** [comment]
PartyA and  PartyB are normal uses and both of them are okay with e.g.x500 in leverage. 

The protocol has three Liquidation Types `NORMAL - LATE - OVERDUE`.

So as a user (PartyA or PartyB ), I should have a chance that my position will be in NORMAL or LATE. because this is how the protocol is designed. but unfortunately with the feature of no max cap in leverage. **It's like saying to the users, use the leverage as you like but you will never be able to receive any profit.** and this risk is not mentioned anywhere.

This is happening because there is no LIQUIDATOR (bot) that could liquidate this position at the right time due to **the market volatility and the big leverage.**   

When you leave the leverage limit to happen naturally. that means you leave every user to try big leverage first and lose his `cva` + profit due to `OVERDUE` Liquidation Type. so next time the user will set his leverage very carefully.

**Summary:** With no max cap in leverage, the user has no chance to receive his profit.

**Comment by panprog** [comment]
PartyB is supposed to be sophisticated market maker, so it should be well aware of the risks of high leverage. And UserA can't open position without partyB.
I also don't see a medium impact here. The different liquidation types are known to all users in advance, so this is just a common sense that very high leverage increases chances of late and overdue liquidations. It's not a problem of the protocol if user wants to take these risks.

**Comment by Ch-301** [comment]
[ideally anyone can become a PartyB](https://discord.com/channels/812037309376495636/1118917849482793071/1120391817859449003) even if supposed to be a sophisticated market maker, and if it was aware of the risks of high leverage. in this protocol, there is another layer of risk by the inevitability of losing the profit with the high leverage and this is not mentioned in the known issues/acceptable risks or in docs.

When you say:
```
...very high leverage increases chances of late and overdue liquidations...
```
It's not just **increases chances**. it's 100% you going lose your profit.

With the current system is impossible to avoid that risk without defining a max leveraging or you can just accept the impact.

**Comment by MoonKnightDev** [comment]
Fixed code PR link:
https://github.com/SYMM-IO/symmio-core/pull/26

**Comment by hrishibhat** [comment]
Result:
Low
Unique
After further review and discussions, partyB is a permissioned(although not fully trusted) role that needs to be registered and agree with Lead Watson comment below that they would be harming themselves by accepting such high leverage. 
Maintaining low severity. 
Lead Watson comment:
> It is better to have a max leverage limit for each market. However, I think it is a low issue here. In the current system, PartyBs are only open to reputable and trusted entities. Assume that a user creates a position with 1000x leverage. If PartyB is willing to accept this position, I believe that they should know that a small price change will result in a significant change in price, which will result in the loss of the positions to be extremely large. So PartyB has to accept the consequence. In other words, it is like PartyB harming themselves by accepting such a high-leverage position.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Ch-301](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/125/#issuecomment-1652302764): rejected

**Comment by Ch-301** [comment]
```
partyB is a permissioned(although not fully trusted) role that needs to be registered
```
It is permission but everyone can ask for the partyB

```
I believe that they should know that a small price change will result in a significant change in price, which will result in the loss of the positions to be extremely large...
```
Nothing new here. It's not about whether they should know or not. the risk of this case (losing your profit) in this protocol is diff and it is exist

When you say: 
```
 ...it is like PartyB harming themselves by accepting such a high-leverage position.
```
As a PartyB I accept the risk that I will lose everything **BUT IN CASE I WIN, WHERE IS MY PROFIT** (I will receive nothing. and this is not mentioned anywhere). I'm playing the game but Im losing everything or my profit in whatever cases. this is not how leveraging should work.

From Sherlock [Docs](https://docs.sherlock.xyz/audits/judging/judging#how-to-identify-a-medium-issue)
```
How to identify a medium issue:
Causes a loss of funds but requires certain external conditions or specific states.
```
PartyB losing the profit (funds) can't be Low
This should be at least medium

**Comment by hrishibhat** [comment]
> As a PartyB I accept the risk that I will lose everything BUT IN CASE I WIN, WHERE IS MY PROFIT (I will receive nothing. and this is not mentioned anywhere). I'm playing the game but Im losing everything or my profit in whatever cases. this is not how leveraging should work.

In that case partyB should choose not to accept high leverage positions right? seems like a simple sanity check to prevent partyB footgun.

**Comment by Ch-301** [comment]
> In that case partyB should choose not to accept high leverage positions right? seems like a simple sanity check to prevent partyB footgun.

In that case, we have something in the README called 
`Please list any known issues/acceptable risks that should not result in a valid finding.`

They can say: In case high leverage positions partyB will never receive any profit if he wins. 

Now, partyB should choose not to accept high-leverage positions.

**Comment by hrishibhat** [comment]
While that would be ideal, it cannot be done for all actions, especially if the protocol thinks its expected behaviour.

**Comment by Ch-301** [comment]
```
...especially if the protocol thinks its expected behaviour.
```
Yeah, I can see it was expected behavior by fixing it. 
We cannot cover up the sun with a sieve. 
Sadly the rules are not respected here.
