### ISSUE TITLE
rvierdiiev - User can avoid unfavorable position closing by deallocating funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#126]
rvierdiiev

high

# User can avoid unfavorable position closing by deallocating funds

## Summary
User can avoid unfavorable position closing by deallocating funds
## Vulnerability Detail
There are 2 cases when position can be closed: when [user requested it](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacetImpl.sol#L148) or when partyB does [emergency close](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L309).

So in first option `fillCloseRequest` function will be closed by partyB, which will check if [both parties are solvent](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L288) after the close.
The same check is present [inside `emergencyClosePosition` function](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L317).

partyA can use this check to make only favorable closes. In case if he sees that this position close is not good for him anymore and will create additional losses, he can forntrun any of `fillCloseRequest` or `emergencyClosePosition` function and deallocate some amount of free funds, which is enough to make `LibSolvency.isSolventAfterClosePosition` function revert and do not allow to close position.
## Impact
User can not allow to close position.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
I don't know the solution here.

**Comment by rvierdiiev** [comment]
Escalate
This is not duplicate of #236
236 says that user can request close of position, when it was open, which will stop emergency close.
while this report describes how partyA can stop closing emergency or not emergency request(partyA request) in unfavorable cases

Moreover, even when 236 will be fixed, this issue will steal hold.
I guess, that this is valid solo high.

**Comment by sherlock-admin2** [comment]
> Escalate
> This is not duplicate of #236
> 236 says that user can request close of position, when it was open, which will stop emergency close.
> while this report describes how partyA can stop closing emergency or not emergency request(partyA request) in unfavorable cases
> 
> Moreover, even when 236 will be fixed, this issue will steal hold.
> I guess, that this is valid solo high.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Emm then user would face the risk liquidation

**Comment by rvierdiiev** [comment]
> Emm then user would face the risk liquidation

User can allocate funds back to avoid it.

**Comment by panprog** [comment]
This should be invalid

> In case if he sees that this position close is not good for him anymore and will create additional losses, he can forntrun any of `fillCloseRequest` or `emergencyClosePosition` function and deallocate some amount of free funds, which is enough to make `LibSolvency.isSolventAfterClosePosition` function revert and do not allow to close position.

This is **not true**. The user can't deallocate funds to become liquidatable, there is a check in the deallocate to ensure partyA is still solvent after deallocation:
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L61C20-L63

The check when deallocating is more strict than `isSolventAfterClosePosition`, because when closing position, the locked balance is released, but when deallocating - it's locked. So it's impossible to deallocate so much funds that `isSolventAfterClosePosition` reverts, but `deallocate` - doesn't revert.

**Comment by rvierdiiev** [comment]
i believe that @panprog is correct.
i have missed that important point, which makes it impossible.
and this report is not duplicate of 236, it's just invalid.
sorry

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non issue

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/126/#issuecomment-1655187696): accepted
