### ISSUE TITLE
Juntao - Allowing a suspended PartyA to force close positions is against design decision and brings risk

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#129]
Juntao

medium

# Allowing a suspended PartyA to force close positions is against design decision and brings risk

## Summary

A suspended PartyA is able to close his/her positions by calling `forceClosePosition(...)` method, this is against design decision and may bring risk.

## Vulnerability Detail

When a PartyA requests to close a position, the request might be ignored by a unresponding PartyB and user's funds is stucked. To prevent this situation from happening, PartyA can call [forceClosePosition(...)](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacet.sol#L152-L169) method to force close the position and get funds back.
```solidity
    function forceClosePosition(uint256 quoteId, PairUpnlAndPriceSig memory upnlSig)
        external
        notLiquidated(quoteId)
        whenNotPartyAActionsPaused
    {
        Quote storage quote = QuoteStorage.layout().quotes[quoteId];
        uint256 filledAmount = quote.quantityToClose;
        uint256 requestedClosePrice = quote.requestedClosePrice;
        PartyAFacetImpl.forceClosePosition(quoteId, upnlSig);
        emit ForceClosePosition(
            quoteId,
            quote.partyA,
            quote.partyB,
            filledAmount,
            requestedClosePrice,
            quote.quoteStatus
        );
    }
```
We can see from the code that this method could be called by anyone, including a suspended PartyA. 

As confirmed with sponsor, suspended partyAs are not allowed to do anything to their positions, however, this can be bypassed by simply calling `forceClosePosition` method and positions are thus closed by a suspended PartyA.

## Impact

- Allowing a suspended PartyA to force close positions is against the design decision
- Allowing a suspended PartyA to force close suspicious positions may result in more ill-gotten gains and make things worse.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacet.sol#L152-L169

## Tool used

Manual Review

## Recommendation

Should not allow a PartyA to call [forceClosePosition(...)](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacet.sol#L152-L169):
```diff
    function forceClosePosition(uint256 quoteId, PairUpnlAndPriceSig memory upnlSig)
        external
+       notSuspended(msg.sender)
        notLiquidated(quoteId)
        whenNotPartyAActionsPaused
    {
        ...
    }
```

Duplicate of #229

**Comment by juntzhan** [comment]
Escalate

I believe this is not a duplicate but a different issue.

This report describes the issue from the aspect of PartyA, a suspended user may cheat again and earn unethical profit (may not be known by others) by force close the position, and this brings extra risk and enlarges the potential loss, if the suspended user is unsuspended in the future, user can withdraw and the loss is permanent.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I believe this is not a duplicate but a different issue.
> 
> This report describes the issue from the aspect of PartyA, a suspended user may cheat again and earn unethical profit (may not be known by others) by force close the position, and this brings extra risk and enlarges the potential loss, if the suspended user is unsuspended in the future, user can withdraw and the loss is permanent.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
the issue is still duplicate of #229 

root cause is lack of notSuspended(msg.sender) modifier

**Comment by juntzhan** [comment]
> In case the same vulnerability appears across multiple places in different contracts, they can be considered duplicates. 
> The exception to this would be if underlying code implementations, impact, and the fixes are different, then they can be treated separately.  

1. Different code implementations
#229 https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacet.sol#L98
#129
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacet.sol#L152-L169

2. Different Impacts (details are described in each report)
#229 malicious partyA can transfer the ill-gotten gains out of the protocol
#129 malicious partyA can not be stopped from continuing doing harm and earn more ill-gotten gains

3. Different fixes (different root causes)
#229 
Add the notSuspended modifier to the openPosition and fillCloseRequest functions
#129
Add the notSuspended modifier to the forceClosePosition function

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #229 
Vulnerability of suspended parties implementing code they are not supposed to. The underlying issue is the same, The code implementation does not change from the vulnerability's POV. suspended parties having access to a function. 
Impact is similar
Fix, is similar too, to not allow suspended parties to execute certain functions. 
While This should have been reported together, the issue is still a duplicate of #229 

Seems like there is some confusion in interpreting the duplication rules, will not this down and see how best it can be improved.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [juntzhan](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/129/#issuecomment-1651765807): rejected
