### ISSUE TITLE
Juntao - Quote may be opened with an invalid symbolId

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#135]
Juntao

medium

# Quote may be opened with an invalid symbolId

## Summary

New quote may be created with an invalid `symbolId`.

## Vulnerability Detail

When PartyA sends a quote, protocol will [check](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacetImpl.sol#L44) if the Symbol is valid and revert if not:
```solidity
        require(symbolLayout.symbols[symbolId].isValid, "PartyAFacet: Symbol is not valid");
```
SymbolId's validation state could be changed by `SYMBOL_MANAGER_ROLE` through [setSymbolValidationState(...)](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/control/ControlFacet.sol#L136C-L144) method:
```solidity
    function setSymbolValidationState(
        uint256 symbolId,
        bool isValid
    ) external onlyRole(LibAccessibility.SYMBOL_MANAGER_ROLE) {
        SymbolStorage.Layout storage symbolLayout = SymbolStorage.layout();
        require(symbolId >= 1 && symbolId <= symbolLayout.lastId, "ControlFacet: Invalid id");
        emit SetSymbolValidationState(symbolId, symbolLayout.symbols[symbolId].isValid, isValid);
        symbolLayout.symbols[symbolId].isValid = isValid;
    }
```
When quote is partially filled by PartyB, a new child quote will be [created](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L199-L223) with the same `symbolId` as its parent:
```solidity
            Quote memory q = Quote({
                ...
                symbolId: quote.symbolId,
                ...
            });
```
However there is no check if the `symbolId` is valid or not, if the `symbolId` was invalidated by `SYMBOL_MANAGER_ROLE` when the parent quote is pending, this new quote may be created with an invalid `symbolId`.

## Impact

New quote may be created with an invalid symbolId.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L199-L223

## Tool used

Manual Review

## Recommendation

Should check if `symbolId` is still valid before createing a new child quote:
```diff
+          require(quote.symbolId.isValid, "PartyAFacet: Symbol is not valid");
            Quote memory q = Quote({
                ...
                symbolId: quote.symbolId,
                ...
            });
```

Duplicate of #122

**Comment by juntzhan** [comment]
Escalate

I believe this is a valid issue as described in the report.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I believe this is a valid issue as described in the report.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Emm

> New quote may be created with an invalid symbolId.

Would kindly ask the auditor to elaborate more on the impact, what is the impact of "quote with invalid symbol id"?

**Comment by ctf-sec** [comment]
duplicate of https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/122

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #122 
The final validity of the issue will be decided on the resolution of #122

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [juntzhan](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/135/#issuecomment-1651740421): accepted
