### ISSUE TITLE
sinarette - Collisions may occur when PartyA and PartyB are liquidated concurrently

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#142]
sinarette

medium

# Collisions may occur when PartyA and PartyB are liquidated concurrently

## Summary

PartyA can be liquidated while one of the corresponding PartyBs has been liquidated. In this case, the open quotes can be either liquidated in PartyA or PartyB, which may occur some collision in the accounting process since the liquidation procedure is slightly different for PartyA and PartyB.

## Vulnerability Detail

When liquidation occurs, whether PartyA or PartyB, the accounted is first marked as liquidated.
Also before liquidation, the LiquidationFacet checks if the account is already marked as liquidated, to avoid liquidation on already liquidated accounts.
```solidity
    /* LiquidationFacet.sol */
    function liquidatePartyA(
        address partyA,
        SingleUpnlSig memory upnlSig
    )
    external
    whenNotLiquidationPaused
    notLiquidatedPartyA(partyA) //@audit Only Check PartyA
    onlyRole(LibAccessibility.LIQUIDATOR_ROLE)

    function liquidatePartyB(
        address partyB,
        address partyA,
        SingleUpnlSig memory upnlSig
    )
    external
    whenNotLiquidationPaused
    notLiquidatedPartyB(partyB, partyA)
    notLiquidatedPartyA(partyA)
    onlyRole(LibAccessibility.LIQUIDATOR_ROLE)
```
However, as you can see, `liquidatePartyB` checks liquidation status for both PartyA and PartyB, but `liquidatePartyA` checks only for PartyA. Therefore, it is possible that PartyB gets liquidated, then the corresponding PartyA also gets liquidated.

After starting the liquidation process, liquidators have to liquidate the open positions for each parties, and the liquidation procedure is slightly different in PartyA and PartyB. If a PartyB and its corresponding PartyA is liquidated concurrently, this may lead to some accounting conflicts depending on the order.

Here is one example of such conflicts:

When a position of PartyB is liquidated, it then unlocks the locked balance of PartyA (close the position):
```solidity
    /* LiquidationFacetImpl.sol # liquidatePositionsPartyB */
        // Marks the position as liquidated
        quote.quoteStatus = QuoteStatus.LIQUIDATED;
        quote.modifyTimestamp = block.timestamp;

        // Close the position, unlock those locked balances
        accountLayout.lockedBalances[partyA].subQuote(quote);

        LibQuote.removeFromOpenPositions(quote.id);
```

However if the same position is liquidated in PartyA, the locked balances of PartyA remains the same until the PartyA is fully liquidated.

```solidity
    /* LiquidationFacetsImpl.sol # liquidatePositionsPartyA */
        if (quoteLayout.partyAPositionsCount[partyA] == 0) {
            // Unlock all the locked balances only after every open positions are liquidated
            accountLayout.allocatedBalances[partyA] = 0;
            accountLayout.lockedBalances[partyA].makeZero();
```

The change in lockedBalances(which is supposed to be unchanged in PartyA liquidation) could make a problem when the liquidation.

```solidity
    /* LiquidationFacetImpl.sol # liquidatePositionsPartyA */
        } else if (
            accountLayout.liquidationDetails[partyA].liquidationType == LiquidationType.LATE
        ) {
            accountLayout.partyBAllocatedBalances[quote.partyB][partyA] +=
                quote.lockedValues.cva -
                ((quote.lockedValues.cva * accountLayout.liquidationDetails[partyA].deficit) /
                    accountLayout.lockedBalances[partyA].cva); // <-- lockedBalance affects the actually gained cva amount
            if (hasMadeProfit) {
                accountLayout.partyBAllocatedBalances[quote.partyB][partyA] -= amount;
            } else {
                accountLayout.partyBAllocatedBalances[quote.partyB][partyA] += amount;
            }
        } ...
```

If the liquidationType is LATE, the actual cva amount gained is calculated as the proportion of the position's cva among the total locked balances' cva (`quote.lockedValues.cva / accountLayout.lockedBalances[partyA].cva`).
However as we saw in `liquidatePositionsPartyB`, the `lockedBalances[partyA]` could be affected when a position is liquidated before in PartyB.
This results in inconsistency in accounting, depending on the order of execution.

## Impact

Liquidation results and accounting could be inconsistent, depending on the order of position liquidations.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L348
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L174-185

## Tool used

Manual Review

## Recommendation

In order to restrict liquidation orders, let the liquidatePositions could not be executed before one side of the parties  is fully liquidated

**Comment by sinarette** [comment]
Escalate

This issue is stating the underlying flaw of the liquidation process - PartyB and corresponding PartyA can be liquidated concurrently, which becomes the essential cause of several issues such as #189.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is stating the underlying flaw of the liquidation process - PartyB and corresponding PartyA can be liquidated concurrently, which becomes the essential cause of several issues such as #189.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
Escalate

This issue is invalid (will underflow), because it assumes that `liquidatePositionsPartyA` can be called after `liquidatePartyB` but before `liquidatePositionsPartyB` removes all quotes, but it's impossible, because:

1. `liquidatePartyB` zeroes out partyB locked balances:
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L300

2. `liquidatePositionsPartyA` will underflow when trying to reduce partyB locked balances (because locked balances are 0):
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L198

#189 is valid and different, because it deallocates partyA before partyB liquidation is finished (not liquidate partyA before partyB liquidation is finished)

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is invalid (will underflow), because it assumes that `liquidatePositionsPartyA` can be called after `liquidatePartyB` but before `liquidatePositionsPartyB` removes all quotes, but it's impossible, because:
> 
> 1. `liquidatePartyB` zeroes out partyB locked balances:
> https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L300
> 
> 2. `liquidatePositionsPartyA` will underflow when trying to reduce partyB locked balances (because locked balances are 0):
> https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L198
> 
> #189 is valid and different, because it deallocates partyA before partyB liquidation is finished (not liquidate partyA before partyB liquidation is finished)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@sinarette Do you have additional comments?

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue due to the revert mentioned in the [escalation](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/142#issuecomment-1654196659)

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [panprog](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/142/#issuecomment-1654196659): accepted
- [sinarette](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/142/#issuecomment-1653293050): rejected
