### ISSUE TITLE
Ch_301 - Users will never receive a profit if the position gets liquidated

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#146]
Ch_301

high

# Users will never receive a profit if the position gets liquidated

## Summary
We have this note from the contest page
```diff
Q: Are there any additional protocol roles? If yes, please explain in detail:
...
LIQUIDATOR_ROLE: Can liquidate users.
SETTER_ROLE: Can change main system settings.
Note: All roles are trusted except for LIQUIDATOR_ROLE.
```

## Vulnerability Detail
SYMM accepts the volatile market with big Open Interest (OI) to Total Value Locked (TVL) Ratios 
e.g.for shorting BTC, SYMM IO has an available OI to TVL ratio of 24.76
So any move could lead directly to `LiquidationType.OVERDU`

Liquidators are a principal component to keeping this system (SYMMIO) in a good healthy state.
The only thing that fuels and incentives them is `liquidationFee`

1- in case `LiquidationType` is `LATE` as Liquidator I need to liquidate this PartyA. 
 The only one here could do that is the PartyB to save his profit but in most cases, PartyB are regular users with no tech background  

2-The worst case for the ecosystem is `LiquidationType.OVERDUE` because Liquidators will never receive any fees, They will just lose their funds (gas) for nothing 
 
## Impact
- Liquidators will not participate in this ecosystem and this will leave SYMM protocol in a bad state
- SYMM protocol does not guarantee the profit of the second side if the position gets liquidated

## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L73-L87
```solidity
            if (availableBalance >= 0) {
                uint256 remainingLf = accountLayout.lockedBalances[partyA].lf;
                accountLayout.liquidationDetails[partyA].liquidationType = LiquidationType.NORMAL;
                accountLayout.liquidationDetails[partyA].liquidationFee = remainingLf;
            } else if (uint256(-availableBalance) < accountLayout.lockedBalances[partyA].lf) {
                uint256 remainingLf = accountLayout.lockedBalances[partyA].lf -
                    uint256(-availableBalance);
                accountLayout.liquidationDetails[partyA].liquidationType = LiquidationType.NORMAL;
                accountLayout.liquidationDetails[partyA].liquidationFee = remainingLf;
            } else if (
                uint256(-availableBalance) <=
                accountLayout.lockedBalances[partyA].lf + accountLayout.lockedBalances[partyA].cva
            ) {
                uint256 deficit = uint256(-availableBalance) -
                    accountLayout.lockedBalances[partyA].lf;
                accountLayout.liquidationDetails[partyA].liquidationType = LiquidationType.LATE;
                accountLayout.liquidationDetails[partyA].deficit = deficit;
            } else {
                uint256 deficit = uint256(-availableBalance) -
                    accountLayout.lockedBalances[partyA].lf -
                    accountLayout.lockedBalances[partyA].cva;
                accountLayout.liquidationDetails[partyA].liquidationType = LiquidationType.OVERDUE;
                accountLayout.liquidationDetails[partyA].deficit = deficit;
            }
            AccountStorage.layout().liquidators[partyA].push(msg.sender);
        }
```
## Tool used

Manual Review

## Recommendation
pay the Liquidators some fees from the `GlobalAppStorage.layout().feeCollector` balance

Duplicate of #234

**Comment by Ch-301** [comment]
Escalate

It's a clear duplicate of #234

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> It's a clear duplicate of #234 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
duplicate of #234

**Comment by hrishibhat** [comment]
Result: 
Medium
Duplicate of #234

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Ch-301](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/146/#issuecomment-1652260204): accepted
