### ISSUE TITLE
mstpr-brainbot - Extreme market situations can halt the liquidations

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#155]
mstpr-brainbot

high

# Extreme market situations can halt the liquidations

## Summary
In certain adverse market conditions, complexities can arise in the liquidation process, leading to unintended consequences. This scenario discusses a situation where both PartyA and a specific PartyB are eligible for liquidation. PartyA, with multiple long positions and one short position, is chosen for liquidation due to higher potential liquidation fees. However, an underflow issue arises during the liquidation process when calculating PartyA's profit from a short position with PartyB. This issue halts the liquidation process as PartyA cannot be fully liquidated and PartyB's liquidation cannot be initiated.
## Vulnerability Detail
Let's assume PartyA has several trades with different PartyBs. Specifically, PartyA holds five long and one short positions with six distinct PartyBs.

Now, imagine the market sentiment is extremely bearish, and all prices are decreasing. PartyA becomes eligible for liquidation due to the long positions. However, the PartyB, with whom PartyA only holds one short position, also becomes eligible for liquidation. Suppose a liquidator opts to liquidate PartyA due to the potential for more liquidation fees (assuming PartyA has more liquidation fees allocated), and this is a NORMAL type liquidation.

Let's further consider that the single short position held between our liquidatable PartyA and liquidatable PartyB has the following locked values: mm:100, cva:20, lf:5, and assume that PartyB has 130 allocated balances. Now, suppose the PnL for this specific trade is -151 for PartyB and +151 for PartyA. With these factors in mind, we proceed with the liquidation of PartyA.

The liquidator's first three steps: liquidatePartyA, setSymbolsPrice, and liquidatePendingPositionsPartyA, should proceed without issues. However, complications arise at the final step, the actual liquidation function, liquidatePositionsPartyA.

Here, all the open quoteIds are looped and finalized. Yet, the following lines will revert for the specific quote id we previously addressed, which was held between the liquidatable PartyB:

```solidity
(bool hasMadeProfit, uint256 amount) = LibQuote.getValueOfQuoteForPartyA(
                accountLayout.symbolsPrices[partyA][quote.symbolId].price,
                LibQuote.quoteOpenAmount(quote),
                quote
            );
            if (hasMadeProfit) {
                accountLayout.totalUnplForLiquidation[partyA] += int256(amount);
            } else {
                accountLayout.totalUnplForLiquidation[partyA] -= int256(amount);
            }

            if (
                accountLayout.liquidationDetails[partyA].liquidationType == LiquidationType.NORMAL
            ) {
                accountLayout.partyBAllocatedBalances[quote.partyB][partyA] += quote
                    .lockedValues
                    .cva;
                if (hasMadeProfit) {
                    accountLayout.partyBAllocatedBalances[quote.partyB][partyA] -= amount;
                } else {
                    accountLayout.partyBAllocatedBalances[quote.partyB][partyA] += amount;
                }
```
For this specific quote ID, we calculate the amount that is in profit or loss for PartyA. As previously mentioned, it's -151$ for PartyB and 151$ for PartyA, hence, hasMadeProfit = true.

Initially, PartyB had a total of 130 allocated balance. However, PartyA's cva is also added, so the total allocated balance for PartyB becomes 150 (130+20). If PartyA is profiting, PartyB's allocated balance will decrease. Given that for this quote PartyA is in profit, we will decrease PartyB's allocated balances by -151, leading to an underflow. PartyB has a total of 150 in locked balance, and the upnl is -151, hence, 150 - 151 = -1. This results in an underflow.

As a consequence, PartyA cannot be fully liquidated because this quote ID can't be settled. Additionally, we can't liquidate PartyB and resume this liquidation due to the following modifier in PartyB's liquidation, notLiquidatedPartyB(partyB, partyA), and notLiquidatedPartyA(partyA). The only way to resume the liquidation is to hope for the price to decrease enough to resolve the underflow.

However, even then it is quite hard and almost impossible because of the following lines in setSymbolPrices
    
```solidity
else {
            require(
                accountLayout.liquidationDetails[partyA].upnl == priceSig.upnl &&
                    accountLayout.liquidationDetails[partyA].totalUnrealizedLoss ==
                    priceSig.totalUnrealizedLoss,
                "LiquidationFacet: Invalid upnl sig"
            );
        }
```

because the upnl is changed, unrealized loss is also changed due to some of the quote ids are already liquidated. Also, even though they would be open, the Binance api updates the prices every 1 second which is quite hard to match the exact same prices for an asset. 
## Impact
Considering the market can act extremely as demonstrated above, this should be a valid high. Also, it should be noted that both partyA and partyB is not liquidated in above issue. 

NOTE:
There is an another issue that I created which is titled as "partyB can dodge liquidation if partyA gets liquidated first", in this issue the key takeaway is that the partyB can dodge its liquidation thanks to liquidation of partyA. If the fix of that issue and this issue is enforcing the liquidators to first liquidatable partyB's, both of the issues I created can be seen as same problem although one describing an advantage for a partyB, and the other is demonstrating an issue where partyA liquidation stucks forever. For me, the issues are seperate and should be validated independently, that's why I am creating this issue as a stand alone one.
## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L20-L238

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibQuote.sol#L100-L120

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacet.sol#L57-L66
## Tool used

Manual Review

## Recommendation
Pls check the "Impact" section 

Duplicate of #241

**Comment by mstpr** [comment]
Escalate

This is a dup of #241.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a dup of #241.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
> Given that for this quote PartyA is in profit, we will decrease PartyB's allocated balances by -151, leading to an underflow. PartyB has a total of 150 in locked balance, and the upnl is -151, hence, 150 - 151 = -1. This results in an underflow.

True

duplicate of #241

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #241

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/155/#issuecomment-1653434324): accepted
