### ISSUE TITLE
0xcrunch - Lack of check on if Symbol is valid when opens a quote

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#163]
0xcrunch

medium

# Lack of check on if Symbol is valid when opens a quote

## Summary

Lack of check on if Symbol is valid when opens a quote.

## Vulnerability Detail

Party A opens a quote with a [symbolId](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacetImpl.sol#L23C17-L23C25), it requires that the Symbol with this symbolId must be valid:
```solidity
        require(symbolLayout.symbols[symbolId].isValid, "PartyAFacet: Symbol is not valid");
```
After this quote has been sent, PartyB can lock and open the quote, during the process, it doesn't check if the Symbol with this symbolId is valid or not. This could be a problem because the Symbol could be invalidated by a Symbol Manager:
```solidity
    function setSymbolValidationState(
        uint256 symbolId,
        bool isValid
    ) external onlyRole(LibAccessibility.SYMBOL_MANAGER_ROLE) {
        SymbolStorage.Layout storage symbolLayout = SymbolStorage.layout();
        require(symbolId >= 1 && symbolId <= symbolLayout.lastId, "ControlFacet: Invalid id");
        emit SetSymbolValidationState(symbolId, symbolLayout.symbols[symbolId].isValid, isValid);
        symbolLayout.symbols[symbolId].isValid = isValid;
    }
```
If the Symbol is invalidated before the quote is opened, then the quote will be opened with an invalid Symbol.

## Impact

Quote could be opened with an invalid Symbol.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L112-L254

## Tool used

Manual Review

## Recommendation

Please consider to add check on if quote is opened with a valid Symbol when PartyB opens a quote.
```diff
        Quote storage quote = quoteLayout.quotes[quoteId];
        require(
            quote.quoteStatus == QuoteStatus.LOCKED ||
            quote.quoteStatus == QuoteStatus.CANCEL_PENDING,
            "PartyBFacet: Invalid state"
        );
        require(block.timestamp <= quote.deadline, "PartyBFacet: Quote is expired");
+        require(symbolLayout.symbols[quote.symbolId].isValid, "PartyAFacet: Symbol is not valid");
```

Duplicate of #122

**Comment by 0xcrunch** [comment]
Escalate

Should be valid and a duplicate of #122

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Should be valid and a duplicate of #122 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Agree, duplicate of #122

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #122

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xcrunch](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/163/#issuecomment-1651775669): accepted
