### ISSUE TITLE
xiaoming90 - Rounding error when dividing liquidation fee

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#243]
xiaoming90

medium

# Rounding error when dividing liquidation fee

## Summary

Some amount of assets will be stuck in the contracts due to rounding errors.

## Vulnerability Detail

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L221

```solidity
File: LiquidationFacetImpl.sol
126:     function liquidatePositionsPartyA(
127:         address partyA,
128:         uint256[] memory quoteIds
129:     ) internal returns (bool) {
..SNIP..
220:             if (lf > 0) {
221:                 accountLayout.allocatedBalances[accountLayout.liquidators[partyA][0]] += lf / 2;
222:                 accountLayout.allocatedBalances[accountLayout.liquidators[partyA][1]] += lf / 2;
223:             }
```

At the end of the liquidation process for PartyA, the liquidation fee will be split into two and they are added to the balance of the liquidator(s) who triggered the `setSymbolsPrice` and `liquidatePositionsPartyA` functions.

If the liquidation fee (LF) is an odd value, dividing it by two will cause a round down. 

Assume that the LF is 9, then 9/2 = 4. 1 will be stuck in the contract.

## Impact

Some assets will be stuck in the contracts.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L221

## Tool used

Manual Review

## Recommendation

Consider sweeping the remaining amount to the last recipient as shown below.

```solidity
if (lf > 0) {
	uint payout = lf / 2
    accountLayout.allocatedBalances[accountLayout.liquidators[partyA][0]] += payout
    accountLayout.allocatedBalances[accountLayout.liquidators[partyA][1]] += (lf - payout)
} 
```

**Comment by SergeKireev** [comment]
Escalate

> 1 will be stuck in the contract.

The maximum loss incurred is 1 wei, with the precision of balances being 18 decimals, this should be low severity

**Comment by eliteWalrus4164** [comment]
Escalate

Only 1 wei is at risk:

> 1 will be stuck in the contract.

This is not considered `material amount of funds`, and thus should be of low severity

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Only 1 wei is at risk:
> 
> > 1 will be stuck in the contract.
> 
> This is not considered `material amount of funds`, and thus should be of low severity

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Emm Agree with the escalation, severity is low

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the escalation that the impact can be considered low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SergeKireev](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/243/#issuecomment-1651512427): accepted

**Comment by naveedinno** [comment]
We think that this amount of error is acceptable. So there won't be any fix for it
