### ISSUE TITLE
xiaoming90 - Ambiguous position index of a quote leading to unexpected errors

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#250]
xiaoming90

medium

# Ambiguous position index of a quote leading to unexpected errors

## Summary

The implementation of the `LibQuote.addToOpenPositions` and `LibQuote.removeFromOpenPositions` functions are incorrect and error-prone, which might cause the position to be removed from the account unexpectedly if a removed or non-existent quote ID is passed into the function. 

## Vulnerability Detail

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibQuote.sol#L58

```solidity
File: LibQuote.sol
58:     function addToOpenPositions(uint256 quoteId) internal {
59:         QuoteStorage.Layout storage quoteLayout = QuoteStorage.layout();
60:         Quote storage quote = quoteLayout.quotes[quoteId];
61: 
62:         quoteLayout.partyAOpenPositions[quote.partyA].push(quote.id);
63:         quoteLayout.partyBOpenPositions[quote.partyB][quote.partyA].push(quote.id);
64: 
65:         quoteLayout.partyAPositionsIndex[quote.id] = quoteLayout.partyAPositionsCount[quote.partyA];
66:         quoteLayout.partyBPositionsIndex[quote.id] = quoteLayout.partyBPositionsCount[quote.partyB][
67:             quote.partyA
68:         ];
69: 
70:         quoteLayout.partyAPositionsCount[quote.partyA] += 1;
71:         quoteLayout.partyBPositionsCount[quote.partyB][quote.partyA] += 1;
72:     }
```

When the quote is first added to the account, the `partyAPositionsCount` is zero, and thus it is placed in position 0.

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibQuote.sol#L74

```solidity
File: LibQuote.sol
74:     function removeFromOpenPositions(uint256 quoteId) internal {
75:         QuoteStorage.Layout storage quoteLayout = QuoteStorage.layout();
76:         Quote storage quote = quoteLayout.quotes[quoteId];
77:         uint256 indexOfPartyAPosition = quoteLayout.partyAPositionsIndex[quote.id];
78:         uint256 indexOfPartyBPosition = quoteLayout.partyBPositionsIndex[quote.id];
79:         uint256 lastOpenPositionIndex = quoteLayout.partyAPositionsCount[quote.partyA] - 1;
80:         quoteLayout.partyAOpenPositions[quote.partyA][indexOfPartyAPosition] = quoteLayout
81:             .partyAOpenPositions[quote.partyA][lastOpenPositionIndex];
82:         quoteLayout.partyAPositionsIndex[
83:             quoteLayout.partyAOpenPositions[quote.partyA][lastOpenPositionIndex]
84:         ] = indexOfPartyAPosition;
85:         quoteLayout.partyAOpenPositions[quote.partyA].pop();
86: 
87:         lastOpenPositionIndex = quoteLayout.partyBPositionsCount[quote.partyB][quote.partyA] - 1;
88:         quoteLayout.partyBOpenPositions[quote.partyB][quote.partyA][
89:             indexOfPartyBPosition
90:         ] = quoteLayout.partyBOpenPositions[quote.partyB][quote.partyA][lastOpenPositionIndex];
91:         quoteLayout.partyBPositionsIndex[
92:             quoteLayout.partyBOpenPositions[quote.partyB][quote.partyA][lastOpenPositionIndex]
93:         ] = indexOfPartyBPosition;
94:         quoteLayout.partyBOpenPositions[quote.partyB][quote.partyA].pop();
95: 
96:         quoteLayout.partyAPositionsIndex[quote.id] = 0;
97:         quoteLayout.partyBPositionsIndex[quote.id] = 0;
98:     }
```

When a quote is removed from the account, the `quoteLayout.partyAPositionsIndex[quote.id]` and `quoteLayout.partyBPositionsIndex[quote.id]` is set to zero. Setting it to zero also means that the removed quote ended up in position 0 after the transaction was executed.

In addition, if a quote does not exist in the first place or is not added to the account, the `quoteLayout.partyBPositionsIndex` and `quoteLayout.partyBPositionsIndex` will return zero because it has not been initialized yet.

This is an issue because when the `quoteLayout.partyBPositionsIndex` and `quoteLayout.partyBPositionsIndex` of a quote return zero, the result is inconclusive and ambiguous. This is because the result of zero can mean any of the following three (3) states, which might cause an unexpected error.

1) Quote exists and is stored in Position 0
2) Quote exists, but removed
3) Non-existent quote (Does not exist in the first place)

For instance, if a removed or non-existent quote ID is passed into the `LibQuote.removeFromOpenPositions` function, the function will not revert. Instead, the quote stored in position zero will end up being removed from the account, which is not the expected outcome.

## Impact

The implementation of the `LibQuote.addToOpenPositions` and `LibQuote.removeFromOpenPositions` functions are incorrect and error-prone, which might cause the position to be removed from the account unexpectedly if a removed or non-existent quote ID is passed into the function. 

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibQuote.sol#L74

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibQuote.sol#L74

## Tool used

Manual Review

## Recommendation

Consider having the first quote in the account starts at position 1 or index 1. Reserve position 0 or index 0 for a non-existent quote or quote that has been removed. 

When the `quoteLayout.partyBPositionsIndex` and `quoteLayout.partyBPositionsIndex` of a quote return zero, the `removeFromOpenPositions` function could revert to avoid any potential error.

**Comment by eliteWalrus4164** [comment]
Escalate

The report is hypothetical and doesn't demonstrate a concrete bug/vulnerability

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The report is hypothetical and doesn't demonstrate a concrete bug/vulnerability

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
@xiaoming9090

**Comment by xiaoming9090** [comment]
@ctf-sec I agree with the sponsor's response. You may close this report.

**Comment by hrishibhat** [comment]
Result:
Low
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SergeKireev](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/250/#issuecomment-1651490397): accepted
