### ISSUE TITLE
xiaoming90 - Cooldown periods initialize to 95129375 Years

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#254]
xiaoming90

medium

# Cooldown periods initialize to 95129375 Years

## Summary

The cooldown periods are initialized to 95129375 years, which could prevent `forceCancelQuote`, `forceCancelCloseRequest`, and `forceClosePosition` functions from working if they were not updated later.

## Vulnerability Detail

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/control/ControlFacet.sol#L17

```solidity
File: ControlFacet.sol
17:     function init(address user, address collateral, address feeCollector) external onlyOwner {
18:         MAStorage.Layout storage maLayout = MAStorage.layout();
19:         GlobalAppStorage.Layout storage appLayout = GlobalAppStorage.layout();
20: 
21:         appLayout.collateral = collateral;
22:         appLayout.balanceLimitPerUser = 500e18;
23:         appLayout.feeCollector = feeCollector;
24:         maLayout.deallocateCooldown = 300;
25:         maLayout.forceCancelCooldown = 3000000000000000; // @audit-info => 95129375 Years
26:         maLayout.forceCloseCooldown = 3000000000000000; // @audit-info => 95129375 Years
27:         maLayout.forceCancelCloseCooldown = 3000000000000000; // @audit-info => 95129375 Years
```

The force cooldowns are initialized to 95129375 years, which could prevent `forceCancelQuote`, `forceCancelCloseRequest`, and `forceClosePosition` functions from working if they were not updated later.

## Impact

If the force-related functions are not working, the user's assets might be locked within the protocols if the counterparty does not respond to the user's request.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/control/ControlFacet.sol#L17

## Tool used

Manual Review

## Recommendation

Consider initializing the cooldown periods to a more reasonable value.

**Comment by CodingNameKiki** [comment]
Escalate

Should be invalid, you can see that there is a comment above the function which states that this are testnet values.

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/control/ControlFacet.sol#L16C1-L16C1

```solidity
    // Just For Testnet
    function init(address user, address collateral, address feeCollector) external onlyOwner {
        MAStorage.Layout storage maLayout = MAStorage.layout();
        GlobalAppStorage.Layout storage appLayout = GlobalAppStorage.layout();

        appLayout.collateral = collateral;
        appLayout.balanceLimitPerUser = 500e18;
        appLayout.feeCollector = feeCollector;
        maLayout.deallocateCooldown = 300;
        maLayout.forceCancelCooldown = 3000000000000000;
        maLayout.forceCloseCooldown = 3000000000000000;
        maLayout.forceCancelCloseCooldown = 3000000000000000;
        maLayout.pendingQuotesValidLength = 15;
        maLayout.liquidatorShare = 80e16;
        maLayout.liquidationTimeout = 600;
        appLayout.hasRole[user][LibAccessibility.DEFAULT_ADMIN_ROLE] = true;
        appLayout.hasRole[user][LibAccessibility.SYMBOL_MANAGER_ROLE] = true;
        appLayout.hasRole[user][LibAccessibility.MUON_SETTER_ROLE] = true;
        appLayout.hasRole[user][LibAccessibility.SETTER_ROLE] = true;
        appLayout.hasRole[user][LibAccessibility.PARTY_B_MANAGER_ROLE] = true;
    }
```

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Should be invalid, you can see that there is a comment above the function which states that this are testnet values.
> 
> https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/control/ControlFacet.sol#L16C1-L16C1
> 
> ```solidity
>     // Just For Testnet
>     function init(address user, address collateral, address feeCollector) external onlyOwner {
>         MAStorage.Layout storage maLayout = MAStorage.layout();
>         GlobalAppStorage.Layout storage appLayout = GlobalAppStorage.layout();
> 
>         appLayout.collateral = collateral;
>         appLayout.balanceLimitPerUser = 500e18;
>         appLayout.feeCollector = feeCollector;
>         maLayout.deallocateCooldown = 300;
>         maLayout.forceCancelCooldown = 3000000000000000;
>         maLayout.forceCloseCooldown = 3000000000000000;
>         maLayout.forceCancelCloseCooldown = 3000000000000000;
>         maLayout.pendingQuotesValidLength = 15;
>         maLayout.liquidatorShare = 80e16;
>         maLayout.liquidationTimeout = 600;
>         appLayout.hasRole[user][LibAccessibility.DEFAULT_ADMIN_ROLE] = true;
>         appLayout.hasRole[user][LibAccessibility.SYMBOL_MANAGER_ROLE] = true;
>         appLayout.hasRole[user][LibAccessibility.MUON_SETTER_ROLE] = true;
>         appLayout.hasRole[user][LibAccessibility.SETTER_ROLE] = true;
>         appLayout.hasRole[user][LibAccessibility.PARTY_B_MANAGER_ROLE] = true;
>     }
> ```

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by securitygrid** [comment]
SETTER_ROLE can update these values to reasonable values.

**Comment by ctf-sec** [comment]
> SETTER_ROLE can update these values to reasonable values.

This is true

I have to agree with the escalation

not because of the testing comments

but because the admin can change the cooldown period anytime to reasonable value

so recommend severity is low

https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/control/ControlFacet.sol#L185

```solidity
    function setDeallocateCooldown(
        uint256 deallocateCooldown
    ) external onlyRole(LibAccessibility.SETTER_ROLE) {
        emit SetDeallocateCooldown(MAStorage.layout().deallocateCooldown, deallocateCooldown);
        MAStorage.layout().deallocateCooldown = deallocateCooldown;
    }

    function setForceCancelCooldown(
        uint256 forceCancelCooldown
    ) external onlyRole(LibAccessibility.SETTER_ROLE) {
        emit SetForceCancelCooldown(MAStorage.layout().forceCancelCooldown, forceCancelCooldown);
        MAStorage.layout().forceCancelCooldown = forceCancelCooldown;
    }

    function setForceCloseCooldown(
        uint256 forceCloseCooldown
    ) external onlyRole(LibAccessibility.SETTER_ROLE) {
        emit SetForceCloseCooldown(MAStorage.layout().forceCloseCooldown, forceCloseCooldown);
        MAStorage.layout().forceCloseCooldown = forceCloseCooldown;
    }

    function setForceCancelCloseCooldown(
        uint256 forceCancelCloseCooldown
    ) external onlyRole(LibAccessibility.SETTER_ROLE) {
        emit SetForceCancelCloseCooldown(
            MAStorage.layout().forceCancelCloseCooldown,
            forceCancelCloseCooldown
        );
        MAStorage.layout().forceCancelCloseCooldown = forceCancelCloseCooldown;
    }
```

**Comment by shaka0x** [comment]
Even if the values were not able to be changed, I don't understand why this could be a valid issue. It is a helper function for testing that only the admin can execute. But does not have to execute it. The admin can set lots of values that might break the protocol, but just having the ability does not mean they are issues, as admin is trusted. I am just trying to understand the reasoning as I skip reporting this kinds of things, but maybe I am doing wrong.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Agree with the above escalation as this issue is a valid low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [CodingNameKiki](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/254/#issuecomment-1651544193): accepted
