### ISSUE TITLE
ast3ros - Liquidator may receive incorrect fee in party B liquidation due to party A liquidation interference

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#276]
ast3ros

medium

# Liquidator may receive incorrect fee in party B liquidation due to party A liquidation interference

## Summary

When party B is in the process of liquidation and party A is also liquidated, the liquidator may receive an incorrect liquidation fee.

## Vulnerability Detail

The liquidation of party B involves two stages: `liquidatePartyB` and `liquidatePositionsPartyB`. These are two different (no atomic) transactions.

- In stage 1 - `liquidatePartyB`, the `partyBPositionLiquidatorsShare` is calculated by the formula `(remainingLf - liquidatorShare)/partyBPositionsCount` (which is the average of lf per position)

        maLayout.partyBPositionLiquidatorsShare[partyB][partyA] =
            (remainingLf - liquidatorShare) /
            quoteLayout.partyBPositionsCount[partyB][partyA];

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L265-L267

- In stage 2: the liquidator receives the amount `partyBPositionLiquidatorsShare` * number of liquidation quotes.

        accountLayout.allocatedBalances[msg.sender] +=
            maLayout.partyBPositionLiquidatorsShare[partyB][partyA] *
            priceSig.quoteIds.length;

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L374-L376

The issue is that party A can be liquidated while party B is in the liquidation process.

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacet.sol#L13-L24

If party A is liquidated and completed between stage 1 and stage 2 of party B’s liquidation (party B stage 1 -> party A liquidate position -> party B stage 2), and party A has a position with party B, then the `partyBPositionLiquidatorsShare` does not reflect the correct Lf per outstanding B position because when party A is liquidated, it reduces the `partyBPositionsCount` and adjusts the `partyBAllocatedBalances`.

        quoteLayout.partyBPositionsCount[quote.partyB][partyA] -= 1;

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L209
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L163-L197

Therefore, the liquidator in stage 2 receives `partyBPositionLiquidatorsShare` which is outdated.

## Impact

The liquidator in stage 2 may receive an incorrect amount of liquidation fee.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L265-L267
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L374-L376
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacet.sol#L13-L24
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L209
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L163-L197

## Tool used

Manual Review

## Recommendation

When party B is liquidating in stage 1, change the status to `LIQUIDATING` and prevent party A from liquidating this position.

**Comment by mstpr** [comment]
Escalate

This is an invalid issue. Above scenario will not happen because this line will underflow

https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L198

When partyB's stage1 liquidation goes through all locked balances of partyB set to 0. That will prevent the liquidation of partyA. In order for partyA to be liquidated the partyB needs to be fully liquidated.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is an invalid issue. Above scenario will not happen because this line will underflow
> 
> https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L198
> 
> When partyB's stage1 liquidation goes through all locked balances of partyB set to 0. That will prevent the liquidation of partyA. In order for partyA to be liquidated the partyB needs to be fully liquidated.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
@thangtranth

**Comment by thangtranth** [comment]
@JeffCX thank you for your noti. 

I have reviewed and agree with escalation.  I am sorry for missing the check.

**Comment by ctf-sec** [comment]
ok

**Comment by hrishibhat** [comment]
Result:
Invalid 
Unique
Considering this a non issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/276/#issuecomment-1653555362): accepted

**Comment by MoonKnightDev** [comment]
Fixed code PR link:
https://github.com/SYMM-IO/symmio-core/pull/22
