### ISSUE TITLE
tsvetanovv - It is possible that `expireQuote` does not iterate through all expired quotes

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#283]
tsvetanovv

medium

# It is possible that `expireQuote` does not iterate through all expired quotes

## Summary

It is possible that `expireQuote` does not iterate through all expired quotes because `i` is `uint8`

## Vulnerability Detail

`expireQuote()` is responsible for marking a batch of quotes as expired. However, its design might lead to a problem when the number of expired quotes exceeds 256.
```solidity
function expireQuote(uint256[] memory expiredQuoteIds) external whenNotPartyAActionsPaused {
        QuoteStatus result;
        for (uint8 i; i < expiredQuoteIds.length; i++) {   
            result = LibQuote.expireQuote(expiredQuoteIds[i]);
            emit ExpireQuote(result, expiredQuoteIds[i]);
        }
    }
```

The `expireQuote` function iterates through an array of expired quote IDs (`expiredQuoteIds`) using an 8-bit unsigned integer (`uint8 i`). In Solidity, a `uint8` can only hold values from 0 to 255. As such, if the `expiredQuoteIds` array length exceeds 256, the function would not be able to process all the elements in the array. This would leave some expired quotes unprocessed, resulting in an inaccurate state representation of the system.

The same problem is seen in `checkPartyBValidationToLockQuote`:
```solidity
for (uint8 index = 0; index < quote.partyBsWhiteList.length; index++) { 
                if (msg.sender == quote.partyBsWhiteList[index]) {
                    isValidPartyB = true;
                    break;
                }
```
The function will fail if the whitelist has more than 255 entries.

## Impact

f the length of `expiredQuoteIds.length` exceeds 255, the increment of the `uint8 index` would cause an overflow and the function call would revert.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacet.sol#L61-L67
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L102-L105

## Tool used

Manual Review

## Recommendation

I recommend changing the data type of the iterator from `uint8` to `uint256`, as these data types can handle a much larger range of values. By making this change, the functions would be able to process any number of expired quotes.

**Comment by cvetanovv** [comment]
Escalate

If the `expiredQuoteIds` array length exceeds 256, the function revert.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> If the `expiredQuoteIds` array length exceeds 256, the function revert.

    You've deleted an escalation for this issue.

**Comment by ctf-sec** [comment]
if it reverts, the user can call the function each time with 255 item in batch

```solidity
function expireQuote(uint256[] memory expiredQuoteIds) external whenNotPartyAActionsPaused {
        QuoteStatus result;
        for (uint8 i; i < expiredQuoteIds.length; i++) {   
            result = LibQuote.expireQuote(expiredQuoteIds[i]);
            emit ExpireQuote(result, expiredQuoteIds[i]);
        }
    }
```

there is no harm
