### ISSUE TITLE
mstpr-brainbot - Rounding issue when closing partial positions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#287]
mstpr-brainbot

medium

# Rounding issue when closing partial positions

## Summary
Potential rounding errors may occur in the protocol's calculation process when a position is partially closed, which could have significant implications. Specifically, this discrepancy emerges due to the use of integer division when updating the locked values. If the closed amount is small enough, this division could round to zero, resulting in no decrease in the locked values, despite a reduction in the position size. This could enable a user to close the entire position without decreasing the locked values if they execute a large number of small closes. Furthermore, these discrepancies can lead to incorrect profit and loss calculations, as these are dependent on the remaining position size. In turn, this could disrupt accurate accounting within the system.
## Vulnerability Detail
When a position is partially closed these lines will cause a rounding error 

```solidity
LockedValues memory lockedValues = LockedValues(
            quote.lockedValues.cva -
                ((quote.lockedValues.cva * filledAmount) / (LibQuote.quoteOpenAmount(quote))),
            quote.lockedValues.mm -
                ((quote.lockedValues.mm * filledAmount) / (LibQuote.quoteOpenAmount(quote))),
            quote.lockedValues.lf -
                ((quote.lockedValues.lf * filledAmount) / (LibQuote.quoteOpenAmount(quote)))
        );
```
Assume the LibQuote.quoteOpenAmount(quote) is equal to 1e21. 
quote.lockedValues.mm = 1e18

that means partyB can close an amount of 9 * 10** 2 which would make the 
`((quote.lockedValues.mm * filledAmount) / (LibQuote.quoteOpenAmount(quote)))` = 0, Hence, the quote values are not decreased. 

However, we see that in the following lines the closed amount and quantityToClose updates according to filled amount.

```solidity
quote.closedAmount += filledAmount;
quote.quantityToClose -= filledAmount;
```

This means that if partyB calls the close position as frequent enough he can manage the close entire position without decreasing the locked values. Furthermore, the pnl calculations are depending on the quotes remaining position, although the locked balances are not decreased the closed position will incremented hence, the accounting checks will also calculate the pnl mistakenly.
## Impact
Since the filled amount must be relatively smaller than the full quantity, partyB needs to call the function thousands of times to achieve a significant change on quote. However, assuming the gas fees are low, it might be worth to call this function many times. 
## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibQuote.sol#L149-L208

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L256-L293
## Tool used

Manual Review

## Recommendation

Duplicate of #251

**Comment by mstpr** [comment]
Escalate 

This is exactly the same issue as #251.

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> This is exactly the same issue as #251. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Agree with escalation

**Comment by hrishibhat** [comment]
Result:
Medium 
Duplicate of #251

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/287/#issuecomment-1652061458): accepted
