### ISSUE TITLE
mrpathfindr - Access Control: Suspended user Positions can be closed due to lack of validation.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#29]
mrpathfindr

medium

# Access Control: Suspended user Positions can be closed due to lack of validation.

## Summary
Malicious users are suspended from participation in the protocol through setSuspendedAddress(). The modifier `notSuspended(address user)` is used to check if a user has been suspended. Although this modifier can be used to prevent malicious users from performing actions on their own accounts, it does not stop other users from performing actions on the behalf of the suspended user. So we must check that partyA is not a suspended account so users do not force close suspended account positions. 

## Vulnerability Detail

If a user is suspended and they have pending close requests, other users are able to force close their positions on their behalf. Suspended account positions should not be force closed under any circumstance. 

## Impact

Other users will be able to force close pending suspended account positions. The impact of this issue is that suspended users will indirectly have access to functions they should not have access to (via non-suspended users acting on their behalf). 

## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacet.sol#L152-L170

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacet.sol#L192-L208

[2023-06-symmetrical-mrpathfindr/symmio-core/contracts/facets/PartyA/PartyAFacet.sol](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacet.sol#L85-L112)

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacet.sol#L152-L170

## Tool used

Manual Review

## Recommendation

It order to mitigate this, we must check that partyA for the quote ID in question is not a suspended account. This can be achieved by utilising the function `isSuspended` declared in `ViewFacet.sol`. To ensure other functions related to closing the quote are also resolved, we place the condition in the commonly used internal function `closeQuote`

```solidity
  function closeQuote(Quote storage quote, uint256 filledAmount, uint256 closedPrice) internal {
        QuoteStorage.Layout storage quoteLayout = QuoteStorage.layout();
        AccountStorage.Layout storage accountLayout = AccountStorage.layout();
        
            if(isSuspended(quote.partyA){
       revert("Cannot fill close request for suspended user");

      }

        quote.modifyTimestamp = block.timestamp;

        LockedValues memory lockedValues = LockedValues(
            quote.lockedValues.cva -
                ((quote.lockedValues.cva * filledAmount) / (LibQuote.quoteOpenAmount(quote))),
            quote.lockedValues.mm -
                ((quote.lockedValues.mm * filledAmount) / (LibQuote.quoteOpenAmount(quote))),
            quote.lockedValues.lf -
                ((quote.lockedValues.lf * filledAmount) / (LibQuote.quoteOpenAmount(quote)))
        );
        accountLayout.lockedBalances[quote.partyA].subQuote(quote).add(lockedValues);
        accountLayout.partyBLockedBalances[quote.partyB][quote.partyA].subQuote(quote).add(
            lockedValues
        );
        quote.lockedValues = lockedValues;

        (bool hasMadeProfit, uint256 pnl) = LibQuote.getValueOfQuoteForPartyA(
            closedPrice,
            filledAmount,
            quote
        );
        if (hasMadeProfit) {
            accountLayout.allocatedBalances[quote.partyA] += pnl;
            accountLayout.partyBAllocatedBalances[quote.partyB][quote.partyA] -= pnl;
        } else {
            accountLayout.allocatedBalances[quote.partyA] -= pnl;
            accountLayout.partyBAllocatedBalances[quote.partyB][quote.partyA] += pnl;
        }

        quote.avgClosedPrice =
            (quote.avgClosedPrice * quote.closedAmount + filledAmount * closedPrice) /
            (quote.closedAmount + filledAmount);

        quote.closedAmount += filledAmount;
        quote.quantityToClose -= filledAmount;

        if (quote.closedAmount == quote.quantity) {
            quote.quoteStatus = QuoteStatus.CLOSED;
            quote.requestedClosePrice = 0;
            removeFromOpenPositions(quote.id);
            quoteLayout.partyAPositionsCount[quote.partyA] -= 1;
            quoteLayout.partyBPositionsCount[quote.partyB][quote.partyA] -= 1;
        } else if (
            quote.quoteStatus == QuoteStatus.CANCEL_CLOSE_PENDING || quote.quantityToClose == 0
        ) {
            quote.quoteStatus = QuoteStatus.OPENED;
            quote.requestedClosePrice = 0;
            quote.quantityToClose = 0; // for CANCEL_CLOSE_PENDING status
        } else {
            require(
                quote.lockedValues.total() >=
                    SymbolStorage.layout().symbols[quote.symbolId].minAcceptableQuoteValue,
                "LibQuote: Remaining quote value is low"
            );
        }
    }

```

Duplicate of #229

**Comment by mrpathfindr** [comment]
Escalate for 10 USDC

If party B is a suspended user, then their position with party A should not be closed. I have shown that this is possible therefore this is a valid issue.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> If party B is a suspended user, then their position with party A should not be closed. I have shown that this is possible therefore this is a valid issue. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
duplicate of https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/229

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #229

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mrpathfindr](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/29/#issuecomment-1651769668): accepted
