### ISSUE TITLE
josephdara - function  ```withdrawCooldownOf``` returns wrong value.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#309]
josephdara

medium

# function  ```withdrawCooldownOf``` returns wrong value.

## Summary
The function  ```withdrawCooldownOf``` is supposed to return the withdraw cooldown of a particular user, however this function does not return the estimated cool down period 

## Vulnerability Detail

```solidity
//@audit-issue does not check the withdraw cooldown for the user, 
 function withdrawCooldownOf(address user) external view returns (uint256) {
        return AccountStorage.layout().withdrawCooldown[user];
    }
```
This because of where the mapping ```withdrawCooldown[user]``` is set, 

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L156
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L68
As we can see, the withdrawCooldown is set to the exact block.timestamp of the deallocation, and where it is used, it was added to another variable to get the cooldown period
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L30-L34 
Hence the output of this function is invalid 
## Impact
Calling the function returns the deallocation timestamp not the cooldown period end of a user
## Tool used

Manual Review

## Recommendation
Update the function to 

```solidity
  function withdrawCooldownOf(address user) external view returns (uint256) {
        return AccountStorage.layout().withdrawCooldown[user] + MAStorage.layout().deallocateCooldown;
    }
```

**Comment by Josephdara** [comment]
Escalate

This issue was omitted, and it is indeed a bug. 
The value returned here is the timestamp of when dealoocation happens
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L68
It does not return the actual withdrawCooldown which is when a user can withdraw
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/ViewFacet.sol#L123

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue was omitted, and it is indeed a bug. 
> The value returned here is the timestamp of when dealoocation happens
> https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L68
> It does not return the actual withdrawCooldown which is when a user can withdraw
> https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/ViewFacet.sol#L123

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
https://docs.sherlock.xyz/audits/judging/judging

> Incorrect values in View functions are by default considered low. 
> Exception: In case any of these incorrect values returned by the view functions are used as a part of a larger function which would result in loss of funds then it would be a valid medium/high depending on the impact.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This is not a valid issue

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [josephdara](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/309/#issuecomment-1653080689): rejected
