### ISSUE TITLE
simon135 - If the fee collector is PartyA  in function `receiveTradingFee` then they will get out trading fees which goes against the supposed spec of the system

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#316]
simon135

medium

# If the fee collector is PartyA  in function `receiveTradingFee` then they will get out trading fees which goes against the supposed spec of the system

## Summary
The FeeCollector 
## Vulnerability Detail
The spec  in the system should be that PartyA should pay funding fees to the protocol
but in `receiveTradingFee` they don't 
```solidity
     uint256 tradingFee = LibQuote.getTradingFee(quoteId);
        accountLayout.allocatedBalances[QuoteStorage.layout().quotes[quoteId].partyA] -= tradingFee;
        accountLayout.balances[GlobalAppStorage.layout().feeCollector] += tradingFee;
```
Note:
 The fee collector is set  not explicitly trusted in The Readme but  the fee collector address is set by the `setter` Role we can't assume that it's trusted/not compromised 
## Impact
steps:
1. Fc(feeCollector) makes a huge position with big `requstedopenedPrice` and should pay a huge fee 
2. since they are PartyA they don't pay for it 
3. They take the pnl and close the position (they can do these many times and get out fees)
the loss of funds for the protocol can be substantial 

## Code Snippet
```solidity
     uint256 tradingFee = LibQuote.getTradingFee(quoteId);
        account layout.allocatedBalances[QuoteStorage.layout().quotes[quoteId].partyA] -= tradingFee;
        accountLayout.balances[GlobalAppStorage.layout().feeCollector] += tradingFee;
```
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/libraries/LibQuote.sol#L142
## Tool used

Manual Review

## Recommendation
Do an extra validation in `recieveTradingFee`  that if its FeeCollector the fee goes to the Admin 
```solidity

if (PartyA!=FeeCollector){
	 accountLayout.balances[GlobalAppStorage.layout().feeCollector] += tradingFee;
}
 accountLayout.balances[GlobalAppStorage.layout().Admin] += tradingFee;
```

**Comment by snn20** [comment]
escalate
#299 states how FeeCollector can change the balance and make the functions revert.
This issue states how FeeCollecotor  can get out  the trading fees 
The recommendation is similar but the impact/invariant broken here is different.

**Comment by sherlock-admin2** [comment]
> escalate
> #299 states how FeeCollector can change the balance and make the functions revert.
> This issue states how FeeCollecotor  can get out  the trading fees 
> The recommendation is similar but the impact/invariant broken here is different.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/299#issuecomment-1653478089

**Comment by hrishibhat** [comment]
Result:
Low
Unique 
This is not a valid issue as feeCollector is the protocol-owned address. The fee is collected and distributed by the protocol

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [snn20](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/316/#issuecomment-1652310608): rejected
