### ISSUE TITLE
simon135 - we never pop of `liquiditor` from the array causing no incentives  for liquiditor after the first liquidation in the system in `liquidatePositionsPartyA`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#325]
simon135

high

# we never pop of `liquiditor` from the array causing no incentives  for liquiditor after the first liquidation in the system in `liquidatePositionsPartyA`

## Summary
we don't pop of the liquidator array which is not supposed to happen 
## Vulnerability Detail
since we never pop the index  of the array the next time user gets liquidated the liquidator will be address (0) which should not be
The impact  is that there is no incentive for the liquidator to liquidate and its breaks the spec in the system that anyone can become a liquidator and possibly get rewards 
steps:
1. First liquidation goes well and liquidators are deleted 
2. the second liquidation will reward address(0)
 https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L224
## Impact
as I said above this is not supposed to be its direct brake of the spec and rewards will be lost/stuck when the liquidator though they were getting rewards 
## Code Snippet
```solidity

       if (lf > 0) {
       	// @audit [0] and [1] liquidity after the first liquidation will be address(0) 
                accountLayout.allocatedBalances[accountLayout.liquidators[partyA][0]] += lf / 2;
                accountLayout.allocatedBalances[accountLayout.liquidators[partyA][1]] += lf / 2;
            }
            // we dont pop off the liquidators in the function instead we just set it to 0 address
            delete accountLayout.liquidators[partyA];


```
## Tool used

Manual Review

## Recommendation
add poping  for the liquidator its as simple as that

**Comment by snn20** [comment]
escalate for 10 
My issue is not explained well but still, it's not a  dup of #234
My report is that if we perform another liquidation for a user without popping off the liquidators' entry from the "liquidator array" after the initial liquidation, there may be no incentives for the liquidators.
ex:
Bob and Steve are liquidators. 
1. Upon liquidating Alice's initial position, they get 5 USDC in rewards. 
2. five days later, Alice has another position. Bob and Steve realize that they won't receive any incentives because `liquidators[partyA][0]` and `liquidators[partyA][1]` are now set to address(0). We didn't remove or update the rewards code for the subsequent indexes in the `liquidators` array or pop them off after performing the initial liquidation.


Causes risk and no incentives for liquidators and this will happen to every address that makes another position after  gettings liquidated

**Comment by sherlock-admin2** [comment]
> escalate for 10 
> My issue is not explained well but still, it's not a  dup of #234
> My report is that if we perform another liquidation for a user without popping off the liquidators' entry from the "liquidator array" after the initial liquidation, there may be no incentives for the liquidators.
> ex:
> Bob and Steve are liquidators. 
> 1. Upon liquidating Alice's initial position, they get 5 USDC in rewards. 
> 2. five days later, Alice has another position. Bob and Steve realize that they won't receive any incentives because `liquidators[partyA][0]` and `liquidators[partyA][1]` are now set to address(0). We didn't remove or update the rewards code for the subsequent indexes in the `liquidators` array or pop them off after performing the initial liquidation.
> 
> 
> Causes risk and no incentives for liquidators and this will happen to every address that makes another position after  gettings liquidated 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
Escalate

The issue is invalid. The liquidators array is deleted entirely, you don't need to pop individual items when you delete entire array, so there will be no address(0) values in the liquidator array.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The issue is invalid. The liquidators array is deleted entirely, you don't need to pop individual items when you delete entire array, so there will be no address(0) values in the liquidator array.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@snn20 Do you have additional comments?

**Comment by snn20** [comment]
@hrishibhat Looking at it now I think it's invalid because of https://docs.soliditylang.org/en/latest/types.html#delete

**Comment by hrishibhat** [comment]
@snn20 Sorry are you saying the issue is invalid or the other escalation?

**Comment by snn20** [comment]
sorry,the issue is invalid

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [snn20](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/325/#issuecomment-1652342673): accepted
- [panprog](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/325/#issuecomment-1654716781): accepted
