### ISSUE TITLE
josephdara - Precision loss due to integer underflow

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#329]
josephdara

medium

# Precision loss due to integer underflow

## Summary
This issue is in the setSymbolsPrice function, Since the LIQUIDATOR_ROLEis untrusted, it can in error pass in a value leading to underflow
## Vulnerability Detail
```solidity
    function setSymbolsPrice(address partyA, PriceSig memory priceSig) internal {
        MAStorage.Layout storage maLayout = MAStorage.layout();
        AccountStorage.Layout storage accountLayout = AccountStorage.layout();

        LibMuon.verifyPrices(priceSig, partyA);
        require(maLayout.liquidationStatus[partyA], "LiquidationFacet: PartyA is solvent");
        require(
             
            priceSig.timestamp <=
                maLayout.liquidationTimestamp[partyA] + maLayout.liquidationTimeout,
            "LiquidationFacet: Expired signature"
        );
        for (uint256 index = 0; index < priceSig.symbolIds.length; index++) {
            accountLayout.symbolsPrices[partyA][priceSig.symbolIds[index]] = Price(
                priceSig.prices[index],
                maLayout.liquidationTimestamp[partyA]
            );
        }

        int256 availableBalance = LibAccount.partyAAvailableBalanceForLiquidation(
            priceSig.upnl,
            partyA
        );
        if (accountLayout.liquidationDetails[partyA].liquidationType == LiquidationType.NONE) {
            accountLayout.liquidationDetails[partyA] = LiquidationDetail({
                liquidationType: LiquidationType.NONE,
                upnl: priceSig.upnl,
                //@audit-issue can enter a positive value here Liquidator is semi trusted, therefore, through error it can input a positive value here

                totalUnrealizedLoss: priceSig.totalUnrealizedLoss,
                deficit: 0,
                liquidationFee: 0
            });
```
If a positive value is set as the priceSig.totalUnrealizedLoss, this value is unchecked as is set successfully
However, down the contract in the function liquidatePositionsPartyA
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L189-L195
## Impact
Here the deficit is divided by the totalUnrealizedLoss however as we see here, There is an unprotected uint256 casting.
```solidity
        accountLayout.partyBAllocatedBalances[quote.partyB][partyA] +=
                        amount -
                        ((amount * accountLayout.liquidationDetails[partyA].deficit) /
                            uint256(-accountLayout.liquidationDetails[partyA].totalUnrealizedLoss));
                }
```
Hence if the totalUnrealizedLoss set above is a positive value, There would be an integer underflow whereby the divisor would be abnormally large leading to a precision loss.
The deficit being deducted would be zero and ```accountLayout.partyBAllocatedBalances[quote.partyB][partyA] +=amount``` no matter how large the deficit.
## Tool used

Manual Review

## Recommendation
Add checks within the contract to ensure that the totalUnrealizedLoss being added by the LIQUIDATOR_ROLE is actually less than zero. 
This report references the assumption given by the project that 
Note: All roles are trusted except for LIQUIDATOR_ROLE.

**Comment by Josephdara** [comment]
Escalate

This issue is a valid issue, It is caused by an unsafe casting from int256 to uint256
It has been excluded from the judging without verification

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is a valid issue, It is caused by an unsafe casting from int256 to uint256
> It has been excluded from the judging without verification

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by MoonKnightDev** [comment]
The totalUnrealizedLoss is provided by the Muon, not the liquidator himself, and it's always equal to or less than zero.

**Comment by Josephdara** [comment]
The totalUnrealizedLoss  is provided by Muon but inputted into the contract by the liquidator himself. 
There is no place in the code that verifies that the totalUnrealizedLoss  is less than or equal to zero and the value cannot be changed.

**Comment by Evert0x** [comment]
@ctf-sec I don't see the impact here, any thoughts?

**Comment by MoonKnightDev** [comment]
If the total UnrealizedLoss is greater than zero, the transaction will be reverted. This is verified by the line LibMuon.verifyPrices(priceSig, partyA);. Thus, if a liquidator submits a positive totalUnrealizedLoss, the transaction will be invalid.

**Comment by panprog** [comment]
@Josephdara 

> The totalUnrealizedLoss is provided by Muon but inputted into the contract by the liquidator himself.

The process is the following:
1. User gets all the necessary values (including totalUnrealizedLoss) from muon app along with the signature of these values 
2. User passes these values and signature into transaction
3. If user changes totalUnrealizedLoss, then signature won't match and transaction will revert (in LibMuon.verifyPrices)

So, yes, you're right that user can pass in any totalUnrealizedLoss value and there is no check that it's negative, but any value that is not provided by muon app will revert due to signature mismatch. And values provided by muon app will be correct (and even if not - it's out of scope of this audit)

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
This is a non-issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [josephdara](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/329/#issuecomment-1653093767): rejected
