### ISSUE TITLE
Lilyjjo - Changing a Symbol's trading fee will result in loss of either user/protocol funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#33]
Lilyjjo

high

# Changing a Symbol's trading fee will result in loss of either user/protocol funds

## Summary

PartyA users pay trading fees when they send a quote and get refunded those fees when they either cancel or close a quote. Both of those actions assume that the trading fee for a Symbol is static during that process. If an admin were to change the trading fee of Symbol with open quotes (which they can do), the refunded amount would be either lower (loss of user funds) or higher (loss of protocol funds) which are both bad.

## Vulnerability Detail

In LibQuote.sol's [`getTradingFee()`](https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/libraries/LibQuote.sol#L122), the Symbol's fee is dynamically grabbed from the Symbol's global storage and is used to determine the size of the trading fee:
```solidity
function getTradingFee(uint256 quoteId) internal view returns (uint256 fee) {
        QuoteStorage.Layout storage quoteLayout = QuoteStorage.layout();
        Quote storage quote = quoteLayout.quotes[quoteId];
        Symbol storage symbol = SymbolStorage.layout().symbols[quote.symbolId];
        if (quote.orderType == OrderType.LIMIT) {
            fee =
                (LibQuote.quoteOpenAmount(quote) * quote.requestedOpenPrice * symbol.tradingFee) /
                1e36;
        } else {
            fee = (LibQuote.quoteOpenAmount(quote) * quote.marketPrice * symbol.tradingFee) / 1e36;
        }
    }
```
This is value can be changed by admins with the `SYMBOL_MANAGER_ROLE` in the ControlFacet.sol's [`setTradingFee()`](https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/control/ControlFacet.sol#L164) function.

PartyA has their trading fees taken/returned in LibQuote.sol's [`returnTradingFee()`](https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/libraries/LibQuote.sol#L135) and [`receiveTradingFee()`](https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/libraries/LibQuote.sol#L142) functions which use the dynamically changing Symbol's trading fee to determine how much to take/return. If an admin were to change a Symbol's trading fee and a quote is cancelled or returned, the returned trading fee will be either smaller or larger than what was originally taken. 

## Impact

Users will receive larger or smaller trading fee refunds, loosing money for either the protocol or users. 

## Tool used

Manual Review

## Recommendation

Either statically record a quote's symbol's trading fee at time of `sendQuote()`, or, only take the fees when a quote position is closed. 

Duplicate of #92

**Comment by panprog** [comment]
Escalate

This is a clear duplicate of #92

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a clear duplicate of #92

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
duplicate of #92

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #92

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [panprog](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/33/#issuecomment-1653884402): accepted
