### ISSUE TITLE
mrpathfindr - Access Control: PartyB can open pending quotes for suspended users.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#35]
mrpathfindr

medium

# Access Control: PartyB can open pending quotes for suspended users.

## Summary
A suspended user who has pending quotes that have not been allocated or locked can have their positions opened by PartyB.

## Vulnerability Detail

Suspended users should not be able to participate in the market while their account is suspended. If at the time of suspension, the user has  quotes that have not been opened, partyB can lock, allocate and open quotes for the suspended user. 

The functions `openPosition`, `lockAndOpenQuote` and `allocateAndLockAndOpenQuote` are all function that will open a quote ID where partyA may be a suspended user. 

## Impact

The impact of this issue is that it gives a suspended account in-direct access to a function of the protocol they should not have access to while their account has been suspended. (i.e the ability to enter the market by opening a position) 

## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacet.sol#L38-L82

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacet.sol#L83-L130

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacet.sol#L150-L190

## Tool used

Manual Review

## Recommendation

Ensure pending quotes are not opened by partyB if partyA is a suspended user. 
This can be achieved with the use of the function `isSuspended` declared in `ViewFacet.sol` We place this condition inside the common function `openPosition` in `PartyBFacetImpl.sol`

```solidity

function openPosition(
        uint256 quoteId,
        uint256 filledAmount,
        uint256 openedPrice,
        PairUpnlAndPriceSig memory upnlSig
    ) internal returns (uint256 currentId) {
        QuoteStorage.Layout storage quoteLayout = QuoteStorage.layout();
        AccountStorage.Layout storage accountLayout = AccountStorage.layout();
        
                   if(isSuspended(quote.partyA){
       revert("Cannot fill close request for suspended user");

      }

        Quote storage quote = quoteLayout.quotes[quoteId];
        require(
            quote.quoteStatus == QuoteStatus.LOCKED ||
            quote.quoteStatus == QuoteStatus.CANCEL_PENDING,
            "PartyBFacet: Invalid state"
        );
        require(block.timestamp <= quote.deadline, "PartyBFacet: Quote is expired");



```

Duplicate of #229

**Comment by mrpathfindr** [comment]
Escalate for 10 USDC 

This is not a duplicate of  https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/229

That issue deals with a vulnerability in withdrawals while this deals with opening pending quotes. Although they have the same root cause, their impact is different and should be treated as separate issues.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC 
> 
> This is not a duplicate of  https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/229
> 
> That issue deals with a vulnerability in withdrawals while this deals with opening pending quotes. Although they have the same root cause, their impact is different and should be treated as separate issues.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Root cause is the same, still duplicate of #229

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #229 
Agree with Lead judge underlying issue is the same. Maintaining duplication

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mrpathfindr](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/35/#issuecomment-1651781739): rejected
