### ISSUE TITLE
0xGoodess - underflows could occur in case deficit is bigger than totalUnrealizedLoss during OVERDUE liquidation at setSymbolsPrice

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#37]
0xGoodess

medium

# underflows could occur in case deficit is bigger than totalUnrealizedLoss during OVERDUE liquidation at setSymbolsPrice

## Summary
underflows occurs in case deficit is bigger than totalUnrealizedLoss during OVERDUE liquidation at `setSymbolsPrice`
## Vulnerability Detail
During OVERDUE liquidation, `partyBAllocatedBalances[[quote.partyB][partyA]` would receive the lftover of the position, after deducing the deficit as a ratio of totalUnrealizedLoss. 

However if deficit is bigger than totalUnrealizedLoss, the subtraction would underflows
`amount -
                        ((amount * accountLayout.liquidationDetails[partyA].deficit) /
                            uint256(-accountLayout.liquidationDetails[partyA].totalUnrealizedLoss));`

```solidity
else if (
                accountLayout.liquidationDetails[partyA].liquidationType == LiquidationType.OVERDUE
            ) {
                if (hasMadeProfit) {
                    accountLayout.partyBAllocatedBalances[quote.partyB][partyA] -= amount;
                } else {
                    accountLayout.partyBAllocatedBalances[quote.partyB][partyA] +=
                        amount -
                        ((amount * accountLayout.liquidationDetails[partyA].deficit) /
                            uint256(-accountLayout.liquidationDetails[partyA].totalUnrealizedLoss));
                }
            }
```

calculation of deficit on OVERDUE liquidation
```solidity
else {
                uint256 deficit = uint256(-availableBalance) -
                    accountLayout.lockedBalances[partyA].lf -
                    accountLayout.lockedBalances[partyA].cva;
                accountLayout.liquidationDetails[partyA].liquidationType = LiquidationType.OVERDUE;
                accountLayout.liquidationDetails[partyA].deficit = deficit;
            }
            AccountStorage.layout().liquidators[partyA].push(msg.sender);
```
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L82-L88

Since `totalUnrealizedLoss` is passed by gateway, there is no bound over `deficit` would be less than totalUnrealizedLoss.

```solidity
        if (accountLayout.liquidationDetails[partyA].liquidationType == LiquidationType.NONE) {
            accountLayout.liquidationDetails[partyA] = LiquidationDetail({
                liquidationType: LiquidationType.NONE,
                upnl: priceSig.upnl,
                totalUnrealizedLoss: priceSig.totalUnrealizedLoss,
                deficit: 0,
                liquidationFee: 0
            })
```
## Impact
OVERDUE liquidation reverts when deficit is bigger than totalUnrealizedLoss.

## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L178-L180

## Tool used

Manual Review

## Recommendation
Consider putting a floor on deficit as `min(totalUnrealizedLoss, accountLayout.liquidationDetails[partyA].deficit)`

**Comment by MoonKnightDev** [comment]
always deficit <= |totalUnrealizedLoss| why?

proof:

assumptions:
availableBalnce = allocatedBalance + upnl - cva - lf
allocatedBalance >= 0
upnl = totalUnrealizedLoss + totalUnrealizedProfit
totalUnrealizedProfit >= 0

deficit = - allocatedBalance - cva - lf
deficit = - allocatedBalance - upnl
deficit <= -upnl

so we have deficit <= - totalUnrealizedLoss - totalUnrealizedProfit
and so deficit <= - totalUnrealizedLoss

**Comment by mstpr** [comment]
Escalate

This is an invalid issue because it's not possible to have deficit bigger than totalUnrealizedLoss. Also sponsor states in the above comment why it is.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is an invalid issue because it's not possible to have deficit bigger than totalUnrealizedLoss. Also sponsor states in the above comment why it is. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
Agree with escalation and sponsor's comment

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
This is a non issue based on the above escalation

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/37/#issuecomment-1653618032): accepted
