### ISSUE TITLE
Ruhum - Party A can prevent a position from being emergency closed

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#52]
Ruhum

medium

# Party A can prevent a position from being emergency closed

## Summary
Party A is able to prevent a position from being emergency closed by frontrunning the tx and increasing their nonce.

## Vulnerability Detail
When a position is emergency closed, the upnl and price are verified:

```sol
    function emergencyClosePosition(uint256 quoteId, PairUpnlAndPriceSig memory upnlSig) internal {
        AccountStorage.Layout storage accountLayout = AccountStorage.layout();
        Quote storage quote = QuoteStorage.layout().quotes[quoteId];
        require(quote.quoteStatus == QuoteStatus.OPENED, "PartyBFacet: Invalid state");
        LibMuon.verifyPairUpnlAndPrice(upnlSig, quote.partyB, quote.partyA, quote.symbolId);
        uint256 filledAmount = LibQuote.quoteOpenAmount(quote);
        quote.quantityToClose = filledAmount;
        quote.requestedClosePrice = upnlSig.price;
        LibSolvency.isSolventAfterClosePosition(quoteId, filledAmount, upnlSig.price, upnlSig);
        accountLayout.partyBNonces[quote.partyB][quote.partyA] += 1;
        accountLayout.partyANonces[quote.partyA] += 1;
        LibQuote.closeQuote(quote, filledAmount, upnlSig.price);
    }
```

The signature is checked using the current nonce of party a:

```sol
    function verifyPairUpnlAndPrice(
        PairUpnlAndPriceSig memory upnlSig,
        address partyB,
        address partyA,
        uint256 symbolId
    ) internal view {
        MuonStorage.Layout storage muonLayout = MuonStorage.layout();
//        require(
//            block.timestamp <= upnlSig.timestamp + muonLayout.upnlValidTime,
//            "LibMuon: Expired signature"
//        );
        bytes32 hash = keccak256(
            abi.encodePacked(
                muonLayout.muonAppId,
                upnlSig.reqId,
                address(this),
                partyB,
                partyA,
                AccountStorage.layout().partyBNonces[partyB][partyA],
                AccountStorage.layout().partyANonces[partyA],
                upnlSig.upnlPartyB,
                upnlSig.upnlPartyA,
                symbolId,
                upnlSig.price,
                upnlSig.timestamp,
                getChainId()
            )
        );
        verifyTSSAndGateway(hash, upnlSig.sigs, upnlSig.gatewaySignature);
    }
```

By frontrunning the tx and increasing their nonce, e.g. by allocating funds, they can cause it to revert since the signature won't be valid anymore:

```sol
    function allocate(uint256 amount) internal {
        AccountStorage.Layout storage accountLayout = AccountStorage.layout();
        require(
            accountLayout.allocatedBalances[msg.sender] + amount <=
            GlobalAppStorage.layout().balanceLimitPerUser,
            "AccountFacet: Allocated balance limit reached"
        );
        require(accountLayout.balances[msg.sender] >= amount, "AccountFacet: Insufficient balance");
        accountLayout.partyANonces[msg.sender] += 1;
        accountLayout.balances[msg.sender] -= amount;
        accountLayout.allocatedBalances[msg.sender] += amount;
    }
```

There won't be any costs to party A for doing this since they can later on deallocate and withdraw their funds.

## Impact
Party A can prevent their position from being emergency closed if they don't like the price at which it will be closed.

## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L313
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibMuon.sol#L180
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L49

## Tool used

Manual Review

## Recommendation
Don't use party A's nonce in the hash.

Duplicate of #233

**Comment by 0xruhum** [comment]
Escalate

This is not a duplicate of #233. While both use nonce increases to prevent an on-chain from being executed, the outcome is different. #233 prevents liquidations while this one prevents emergency closings. I've reported a duplicate of 233 myself: #52

As described in the Sherlock docs:
> In case the same vulnerability appears across multiple places in different contracts, they can be considered duplicates. 
The exception to this would be if underlying code implementations, impact, and the fixes are different, then they can be treated separately.

1. Code implementations are different. Two different functionalities are impacted
2. Impact is different. One prevents liquidations the other positions from being closed.
3. Fixes are different. For #233 you have to remove the nonce from [`verifyPartyAUpnl()`](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibMuon.sol#L99). For #52 you remove the nonce from [`verifyPartyAUpnlAndPrice`](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibMuon.sol#L124).

If the protocol team only reads the final report and fixes the issue reported in #233, they'll miss the issue described here. That would leave their contracts vulnerable to the attack.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is not a duplicate of #233. While both use nonce increases to prevent an on-chain from being executed, the outcome is different. #233 prevents liquidations while this one prevents emergency closings. I've reported a duplicate of 233 myself: #52
> 
> As described in the Sherlock docs:
> > In case the same vulnerability appears across multiple places in different contracts, they can be considered duplicates. 
> The exception to this would be if underlying code implementations, impact, and the fixes are different, then they can be treated separately.
> 
> 1. Code implementations are different. Two different functionalities are impacted
> 2. Impact is different. One prevents liquidations the other positions from being closed.
> 3. Fixes are different. For #233 you have to remove the nonce from [`verifyPartyAUpnl()`](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibMuon.sol#L99). For #52 you remove the nonce from [`verifyPartyAUpnlAndPrice`](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibMuon.sol#L124).
> 
> If the protocol team only reads the final report and fixes the issue reported in #233, they'll miss the issue described here. That would leave their contracts vulnerable to the attack.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
The root cause is the same

so I recommend still maintain the duplicates

issue #65, #84, #298 describes the same issue but still consider the duplicates of #233 as well

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #233 
Maintaining duplications as is. The code implementation from the vulnerability POV is the same, front-run a function to increase the nonce, the impact is similar, blocking certain actions and the fix is the same to remove the nonce from the function. 
While I agree that these with the final point in the escalation but these issues should have been combined.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xruhum](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/52/#issuecomment-1655285546): accepted
