### ISSUE TITLE
Yuki - Loss of funds duo to wrong accounting of decimals when changing collateral.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#64]
Yuki

high

# Loss of funds duo to wrong accounting of decimals when changing collateral.

## Summary
Changing the collateral leads to the wrong accounting of the existing balances duo to decimals difference between USDC and USDT. 

## Vulnerability Detail

On the sherlock contest page, it is shown the symmetrical protocol can interact with both USDC and USDT tokens. Which has different decimals on the most chains: USDC - 18 decimals, USDT - 6 decimals.

<img width="591" alt="Screenshot 2023-06-26 at 13 35 29" src="https://github.com/SilentYuki/Symmetrical/assets/135425690/4d879991-3fd0-48b7-acbe-41ee6e0a49ab">

By looking at the protocol design, the amount which is added to the users balances is calculated in 18 decimals, so everything will work fine and the decimals of the tokens won't matter here.

<img width="638" alt="Screenshot 2023-06-16 at 13 54 29" src="https://github.com/SilentYuki/Symmetrical/assets/135425690/5d88a97d-edee-4b1b-ab6a-aeb297387036">
<img width="695" alt="Screenshot 2023-06-16 at 14 26 11" src="https://github.com/SilentYuki/Symmetrical/assets/135425690/238dd03c-09e7-40cb-bcb4-da2058cd7192">

The problem occurs when the protocol team wants to change the collateral between USDC or USDT.
This will lead to the wrong accounting of the existing balances, as they will no longer be calculated based on the old decimals but the new ones.

<img width="444" alt="Screenshot 2023-06-26 at 13 46 34" src="https://github.com/SilentYuki/Symmetrical/assets/135425690/e5500997-32ac-400f-87b4-05c1b294365b">

## Impact
Wrong accounting of the existing balances duo to decimal difference.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L27

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/control/ControlFacet.sol#L95

## Tool used

Manual Review

## Recommendation
As how it is right now, the protocol design doesn't allow changing the collateral when there are existing balances.
The code should be changed or the function setCollateral should be removed.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue should be a duplicate of #249
> 
> Btw sorry for the screenshots not showing, seems like a github problem between private and public repos.
> 
> # Loss of funds duo to wrong accounting of decimals when changing collateral.
> 
> ## Summary
> Changing the collateral leads to the wrong accounting of the existing balances duo to decimals difference between USDC and USDT.
> 
> ## Vulnerability Detail
> On the sherlock contest page, it is shown the symmetrical protocol can interact with both USDC and USDT tokens. Which has different decimals on the most chains: USDC - 18 decimals, USDT - 6 decimals.
> 
> <img width="611" alt="Screenshot 2023-07-04 at 13 49 17" src="https://github.com/SilentYuki/Portfolio/assets/135425690/b99ab9db-2cd3-4116-a022-8d07b2545121">
> 
> By looking at the protocol design, the amount which is added to the users balances is calculated in 18 decimals, so everything will work fine and the decimals of the tokens won't matter here.
> 
> ```solidity
>     function deposit(address user, uint256 amount) internal {
>         GlobalAppStorage.Layout storage appLayout = GlobalAppStorage.layout();
>         IERC20(appLayout.collateral).safeTransferFrom(msg.sender, address(this), amount);
>         uint256 amountWith18Decimals = (amount * 1e18) /
>         (10 ** IERC20Metadata(appLayout.collateral).decimals());
>         AccountStorage.layout().balances[user] += amountWith18Decimals;
>     }
> ```
> ```solidity
>     function withdraw(address user, uint256 amount) internal {
>         AccountStorage.Layout storage accountLayout = AccountStorage.layout();
>         GlobalAppStorage.Layout storage appLayout = GlobalAppStorage.layout();
>         require(
>             block.timestamp >=
>             accountLayout.withdrawCooldown[msg.sender] + MAStorage.layout().deallocateCooldown,
>             "AccountFacet: Cooldown hasn't reached"
>         );
>         uint256 amountWith18Decimals = (amount * 1e18) /
>         (10 ** IERC20Metadata(appLayout.collateral).decimals());
>         accountLayout.balances[msg.sender] -= amountWith18Decimals;
>         IERC20(appLayout.collateral).safeTransfer(user, amount);
>     }
> ```
> The problem occurs when the protocol team wants to change the collateral between USDC or USDT.
> This will lead to the wrong accounting of the existing balances, as they will no longer be calculated based on the old decimals but the new ones.
> 
> ```solidity
>     function setCollateral(
>         address collateral
>     ) external onlyRole(LibAccessibility.DEFAULT_ADMIN_ROLE) {
>         GlobalAppStorage.layout().collateral = collateral;
>         emit SetCollateral(collateral);
>     }
> ```
> 
> ## Impact
> Wrong accounting of the existing balances duo to decimal difference.
> 
> ## Code Snippet
> https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L27
> 
> https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/control/ControlFacet.sol#L95
> 
> ## Tool used
> 
> Manual Review
> 
> ## Recommendation
> As how it is right now, the protocol design doesn't allow changing the collateral when there are existing balances.
> The code should be changed or the function setCollateral should be removed.

    You've deleted an escalation for this issue.

**Comment by securitygrid** [comment]
The `amount` parameter of `deposit` is based on the decimal of the collateral, even if the collateral changes, it will not affect the result due to [here](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/ facets/Account/AccountFacetImpl.sol#L35-L36) The result is always based on e18.

**Comment by CodingNameKiki** [comment]
@securitygrid that's correct, was baited from the same title on #249
