### ISSUE TITLE
Yuki - Force closing a position won't work when the order type is MARKET.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#70]
Yuki

medium

# Force closing a position won't work when the order type is MARKET.

## Summary
Force closing a position won't work when the order type is MARKET.

## Vulnerability Detail
Duo to the require statement applied, force closing a position is only possible if the order type is LIMIT, which shouldn't be like this.

<img width="708" alt="Screenshot 2023-06-16 at 20 31 30" src="https://github.com/SilentYuki/Symmetrical/assets/135425690/b008d435-a966-4acf-a055-c18608f425ff">

The difference between LIMIT and MARKET orders when closing a position. Is that the MARKET order requires that the whole quantity of the Quote is being closed, while the LIMIT can be partially closed. 

<img width="676" alt="Screenshot 2023-06-26 at 18 45 35" src="https://github.com/SilentYuki/Symmetrical/assets/135425690/9592c5de-0750-4879-a30a-34710330e91d">

Generally there shouldn't be restrictions regarding MARKET orders when force closing a position, which means that this is a bug in the protocol design.

## Impact
Force closing a position won't work when the order type is MARKET.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacetImpl.sol#L253

## Tool used

Manual Review

## Recommendation
Consider removing the require statement, as both LIMIT and MARKET orders should be permitted to be force closed as a position.

**Comment by CodingNameKiki** [comment]
Escalate

This issue should be valid medium, as force closing shouldn't be restricted to LIMIT orders only.

Even the sponsor confirmed it's a bug to not have it there.

<img width="1134" alt="Screenshot 2023-07-26 at 14 34 28" src="https://github.com/sherlock-audit/2023-06-symmetrical-judging/assets/112419701/5cbc2de0-7717-41f1-a49a-636bb7aa6ad1">

Btw sorry for the screenshots not showing, seems like a github problem between private and public repos.

# Force closing a position won't work when the order type is MARKET.

## Summary
Force closing a position won't work when the order type is MARKET.

## Vulnerability Detail
Duo to the require statement applied, force closing a position is only possible if the order type is LIMIT, which shouldn't be like this.

```solidity
    function forceClosePosition(uint256 quoteId, PairUpnlAndPriceSig memory upnlSig) internal {
        AccountStorage.Layout storage accountLayout = AccountStorage.layout();
        MAStorage.Layout storage maLayout = MAStorage.layout();
        Quote storage quote = QuoteStorage.layout().quotes[quoteId];

        uint256 filledAmount = quote.quantityToClose;
        require(quote.quoteStatus == QuoteStatus.CLOSE_PENDING, "PartyAFacet: Invalid state");
        require(
            block.timestamp > quote.modifyTimestamp + maLayout.forceCloseCooldown,
            "PartyAFacet: Cooldown not reached"
        );
        require(block.timestamp <= quote.deadline, "PartyBFacet: Quote is expired");
        require(
            quote.orderType == OrderType.LIMIT,
            "PartyBFacet: Quote's order type should be LIMIT"
        );
        if (quote.positionType == PositionType.LONG) {
            require(
                upnlSig.price >=
                    quote.requestedClosePrice +
                        (quote.requestedClosePrice * maLayout.forceCloseGapRatio) /
                        1e18,
                "PartyAFacet: Requested close price not reached"
            );
        } else {
            require(
                upnlSig.price <=
                    quote.requestedClosePrice -
                        (quote.requestedClosePrice * maLayout.forceCloseGapRatio) /
                        1e18,
                "PartyAFacet: Requested close price not reached"
            );
        }

        LibMuon.verifyPairUpnlAndPrice(upnlSig, quote.partyB, quote.partyA, quote.symbolId);
        LibSolvency.isSolventAfterClosePosition(
            quoteId,
            filledAmount,
            quote.requestedClosePrice,
            upnlSig
        );
        accountLayout.partyANonces[quote.partyA] += 1;
        accountLayout.partyBNonces[quote.partyB][quote.partyA] += 1;
        LibQuote.closeQuote(quote, filledAmount, quote.requestedClosePrice);
    }
```
The difference between LIMIT and MARKET orders when closing a position. Is that the MARKET order requires that the whole quantity of the Quote is being closed, while the LIMIT can be partially closed.

```solidity
        if (quote.orderType == OrderType.LIMIT) {
            require(quote.quantityToClose >= filledAmount, "PartyBFacet: Invalid filledAmount");
        } else {
            require(quote.quantityToClose == filledAmount, "PartyBFacet: Invalid filledAmount");
        }
```
Generally there shouldn't be restrictions regarding MARKET orders when force closing a position, which means that this is a bug in the protocol design.

## Impact
Force closing a position won't work when the order type is MARKET.

## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacetImpl.sol#L253

## Tool used

Manual Review

## Recommendation
Consider removing the require statement, as both LIMIT and MARKET orders should be permitted to be force closed as a position.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue should be valid medium, as force closing shouldn't be restricted to LIMIT orders only.
> 
> Even the sponsor confirmed it's a bug to not have it there.
> 
> <img width="1134" alt="Screenshot 2023-07-26 at 14 34 28" src="https://github.com/sherlock-audit/2023-06-symmetrical-judging/assets/112419701/5cbc2de0-7717-41f1-a49a-636bb7aa6ad1">
> 
> Btw sorry for the screenshots not showing, seems like a github problem between private and public repos.
> 
> # Force closing a position won't work when the order type is MARKET.
> 
> ## Summary
> Force closing a position won't work when the order type is MARKET.
> 
> ## Vulnerability Detail
> Duo to the require statement applied, force closing a position is only possible if the order type is LIMIT, which shouldn't be like this.
> 
> ```solidity
>     function forceClosePosition(uint256 quoteId, PairUpnlAndPriceSig memory upnlSig) internal {
>         AccountStorage.Layout storage accountLayout = AccountStorage.layout();
>         MAStorage.Layout storage maLayout = MAStorage.layout();
>         Quote storage quote = QuoteStorage.layout().quotes[quoteId];
> 
>         uint256 filledAmount = quote.quantityToClose;
>         require(quote.quoteStatus == QuoteStatus.CLOSE_PENDING, "PartyAFacet: Invalid state");
>         require(
>             block.timestamp > quote.modifyTimestamp + maLayout.forceCloseCooldown,
>             "PartyAFacet: Cooldown not reached"
>         );
>         require(block.timestamp <= quote.deadline, "PartyBFacet: Quote is expired");
>         require(
>             quote.orderType == OrderType.LIMIT,
>             "PartyBFacet: Quote's order type should be LIMIT"
>         );
>         if (quote.positionType == PositionType.LONG) {
>             require(
>                 upnlSig.price >=
>                     quote.requestedClosePrice +
>                         (quote.requestedClosePrice * maLayout.forceCloseGapRatio) /
>                         1e18,
>                 "PartyAFacet: Requested close price not reached"
>             );
>         } else {
>             require(
>                 upnlSig.price <=
>                     quote.requestedClosePrice -
>                         (quote.requestedClosePrice * maLayout.forceCloseGapRatio) /
>                         1e18,
>                 "PartyAFacet: Requested close price not reached"
>             );
>         }
> 
>         LibMuon.verifyPairUpnlAndPrice(upnlSig, quote.partyB, quote.partyA, quote.symbolId);
>         LibSolvency.isSolventAfterClosePosition(
>             quoteId,
>             filledAmount,
>             quote.requestedClosePrice,
>             upnlSig
>         );
>         accountLayout.partyANonces[quote.partyA] += 1;
>         accountLayout.partyBNonces[quote.partyB][quote.partyA] += 1;
>         LibQuote.closeQuote(quote, filledAmount, quote.requestedClosePrice);
>     }
> ```
> The difference between LIMIT and MARKET orders when closing a position. Is that the MARKET order requires that the whole quantity of the Quote is being closed, while the LIMIT can be partially closed.
> 
> ```solidity
>         if (quote.orderType == OrderType.LIMIT) {
>             require(quote.quantityToClose >= filledAmount, "PartyBFacet: Invalid filledAmount");
>         } else {
>             require(quote.quantityToClose == filledAmount, "PartyBFacet: Invalid filledAmount");
>         }
> ```
> Generally there shouldn't be restrictions regarding MARKET orders when force closing a position, which means that this is a bug in the protocol design.
> 
> ## Impact
> Force closing a position won't work when the order type is MARKET.
> 
> ## Code Snippet
> https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyA/PartyAFacetImpl.sol#L253
> 
> ## Tool used
> 
> Manual Review
> 
> ## Recommendation
> Consider removing the require statement, as both LIMIT and MARKET orders should be permitted to be force closed as a position.
> 
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Emm based on the screenshot (chat history from the sponsor)

seems like there is a tradeoff (pros and cons) to implement the force close in MARKET order type

then we should consider not implementing force close for market order type a design choice, not a bug

**Comment by CodingNameKiki** [comment]
Seems like the protocol will consider allowing Market orders to be force closed.

Not sure if its counted as a bug, leaving the decision to the Sherlock team.

<img width="678" alt="Screenshot 2023-07-28 at 16 25 20" src="https://github.com/sherlock-audit/2023-06-symmetrical-judging/assets/112419701/86177425-e319-40eb-a5f0-9b369d8e4c6f">

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Not being able to force close a market order is a design choice based on the conversation with the Sponsor. While the decision can be debatable, Don't see this as medium severity since this is specific to the protocol implementation. 
Some more context on #277 
Not penalizing the escalation because i can see some ambiguity in the messages

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [CodingNameKiki](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/70/#issuecomment-1651629335): accepted
